### ISSUE TITLE
%e line break not working for "Song placeholder"

### ISSUE THREAD

**Issue by EpicLPer** [univrsal/tuna#100]
I'd love to simplify and declutter my OBS Sources a little bit and tried just using one text source for the "Currently playing: (line break) Artist - Song Title", however the %e linebreak does not seem to work when there's no song playing.

Would be cool if this could be implemented too, thanks :)

**Comment by univrsal** [comment]
added in 6c8a9c0436dfffe267e7b6bc19df380499af30ea
