### ISSUE TITLE
Covers unavailable with last.fm backend

### ISSUE THREAD

**Issue by Shinmera** [univrsal/tuna#101]
**Describe the bug**
When using the last.fm backend, title, album, and so forth are available fine, but the cover does not load.

**To Reproduce**
1. Set up last.fm with a username and API token
2. Make sure to check download cover
3. Play some music that's scrobbled
3. Check downloaded cover file

**Expected behavior**
The cover is loaded.

**Log**
[log.txt](https://github.com/univrsal/tuna/files/5731043/log.txt)

**Comment by univrsal** [comment]
Fixed in 9128f74

**Comment by Shinmera** [comment]
Nice, thanks a lot!
