### ISSUE TITLE
[MPD] It is not clear what directory to choose for the cover

### ISSUE THREAD

**Issue by sim590** [univrsal/tuna#103]
I have my music structured in a directory like so:

```
~/Musique
├── 009 Sound System
│   └── With a Spirit.mp3
...
│       ├── 03 Florence.mp3
│       ├── 04 La tristesse.mp3
│       ├── 05 Les indignés.mp3
│       ├── 06 Petits trous.mp3
│       ├── 07 Un jour viendra.mp3
│       ├── 08 Je plane.mp3
│       ├── 09 Le refus.mp3
│       ├── 10 Ti-gars.mp3
│       ├── 11 J'ai perdu mes amis.mp3
│       ├── 12 La fin du monde.mp3
│       └── cover.jpg
├── Anti-Heros vs Dropkick Murphys
│   └── TKO Records Presents the 1998 Street Punk Title Bout
│       ├── 01 Election Day (live).mp3
│       ├── 02 Rich People Don't Go to Jail.mp3
│       ├── 03 The Road of the Righteous.mp3
│       ├── 04 The Guns of Brixton.mp3
│       └── cover.jpg
├── Arcangelo
...
```

Some directories have a cover and other don't. It's the actual result if managing your music with [beets][].

When I set the directory to `~/Musique`, it doesn't work: the cover is not found. As a reference, the [mpd plugin for AwesomeWM by Lain][lain] does find the file by just using the mpd's information about the file being played and looking for a file matching pattern [`*\\.(jpg|jpeg|png|gif)$`][cover-pattern]. Is that what tuna tries to do? If so, then there may be a bug. Otherwise, I don't know what directory to specify in the MPD tab and how tuna tries to find the cover.

[beets]: https://github.com/beetbox/beets
[lain]: https://github.com/lcpz/lain/blob/master/widget/mpd.lua#L109-L111
[cover-pattern]: https://github.com/lcpz/lain/blob/master/widget/mpd.lua#L30

**Comment by univrsal** [comment]
It should be the root directory that mpd indexes for music. mpd only returns paths relative to that, so to recontruct the full file path again the plugin needs the root directory.

**Comment by sim590** [comment]
OK. The music directory I have configured in `mpd.conf` is:

```
music_directory		"~/Musique"
```

Therefore, I should provide more logs I guess? Here's the log from the last launch of the program.

[2021-01-02 15-56-00.txt](https://github.com/univrsal/tuna/files/5760852/2021-01-02.15-56-00.txt)

**Comment by univrsal** [comment]
I assume you selected the path with the file browser? It has to be an absolute path and end with a '/'. Also mpd is running on the same machine, right?

**Comment by sim590** [comment]
> I assume you selected the path with the file browser?

Yes.

> It has to be an absolute path and end with a '/'.

It does.

![path](https://user-images.githubusercontent.com/4147254/103466713-4576d600-4d15-11eb-975c-61bf297023a6.png)

> Also mpd is running on the same machine, right?

Yes as you can notice from the above screen capture.

Additionally, I want to point out that the info is working fine. Just the cover is missing.

![info-working](https://user-images.githubusercontent.com/4147254/103466689-18c2be80-4d15-11eb-9f1f-8896f621f42c.png)

**Comment by univrsal** [comment]
Seems like there's some issues with discovering cover art. If it's embedded in the file it works fine.

**Comment by sim590** [comment]
Could there be something wrong [here](https://github.com/univrsal/tuna/blob/c2d792c4728d96d05b7d954c109b0b937a01d2ed/src/query/mpd_source.cpp#L200-L203)?

**Comment by univrsal** [comment]
It's most likely [here](https://github.com/univrsal/tuna/blob/c2d792c4728d96d05b7d954c109b0b937a01d2ed/src/util/cover_tag_handler.cpp#L186)

**Comment by sim590** [comment]
I just ran OBS in a terminal and I'm seeing these messages:

```
error: [tuna] local mpd connection on default port (usually 6600) failed with error 'Failed to resolve host name'
```

So in the beginning, I first did select "local connection" but I was not getting any result. Then, I did select "remote connection" for setting the port and I was getting positive result for metadata info, but no cover (as expected).  But then I finally reverted to "local connection" afterwards and it seems like the plugin entered an "in between" state where it continued to get metadata info but no cover were retrieved. So, then when I restarted tuna (in the main tab), I saw the connection issue messages. Therefore, I understood that there was a connection issue in "local connection" mode. However, my MPD server is running on the good port (`mshvlm` is a synonym for 6600) :

```
$ lsof -i
...
mpd          1403 simon   10u  IPv4     1365      0t0  TCP localhost:mshvlm (LISTEN)
mpd          1403 simon   21u  IPv4    46301      0t0  TCP localhost:mshvlm->localhost:49910 (ESTABLISHED)
mpd          1403 simon   22u  IPv4    51787      0t0  TCP localhost:mshvlm->localhost:49912 (ESTABLISHED)
mpd          1403 simon   23u  IPv4    57350      0t0  TCP localhost:mshvlm->localhost:49918 (ESTABLISHED)
mpd          1403 simon   24u  IPv4 27141286      0t0  TCP localhost:mshvlm->localhost:52672 (ESTABLISHED)
...
```

I'm not sure what is the problem, but I hope this can help determine the problem.

**Comment by sim590** [comment]
I just ran the following:

```
env MPD_HOST=localhost obs
```

and I'm not getting connection issue messages anymore. But the cover doesn't seem to be updated.

**Comment by sim590** [comment]
OK. So by forcing the `MPD_HOST` variable like in the above command and selecting another song, the cover was found. I guess that this my fault for this.

However, it doesn't find the cover for some songs. I think that it can find embedded covers, but it has trouble with covers not embedded. Would that be due to #58 ?

**Comment by univrsal** [comment]
No VLC and MPD are handled differently. VLC caches the cover to a folder and returns the path when the cover is requested. I already found the issue and fixed it.

**Comment by sim590** [comment]
Is the fix already in `master` ?

**Comment by univrsal** [comment]
no I haven't pushed it yet

**Comment by sim590** [comment]
I just tried the changes you pushed. There seems to be a bug that was just introduced by your fix. The file pointed to for retrieving the artist (with token `%m`) is growing. It seems like updates to this file are now appended instead of replacing the old content.

**Comment by sim590** [comment]
Here's the result on screen:

![Capture d’écran du 2021-01-02 18-08-05](https://user-images.githubusercontent.com/4147254/103468283-7eb74200-4d25-11eb-8d2b-602f4364046a.png)

Your fix is indeed there, but there's the additional bug.

**Comment by univrsal** [comment]
I think this should be fixed by now, if not just let me know.
