### ISSUE TITLE
Feature Request: field for person who added a song to a Spotify Playlist

### ISSUE THREAD

**Issue by ghost** [univrsal/tuna#106]
First off - I'd like to thank you guys for this great plugin! Christmas days in the home-office felt more together thanks to OBS and a collaborative Spotify playlist! You guys added so much value!

**Describe the bug**
Currently, it's possibly to show a lot of data when a song is played through Spotify. It would be so great if we could add the name of the user who added a song to this playlist. Not sure if that's possible as it's visible in the playlist view, but not in the "currently playing" view.

**Screenshot**
<img width="377" alt="2021-01-06 10_34_35-Spotify Premium" src="https://user-images.githubusercontent.com/63240133/103754614-dcd97300-500c-11eb-9839-06010f6b7379.png">

**Comment by univrsal** [comment]
I took a look at this a  while ago and the problem is that this information isn't directly retrievable so it has to be done over multiple requests to the spotify api and I'd like to keep the request process as simple as possible so I'll not implement this unless there's more demand for it.
