### ISSUE TITLE
Release 1.5.4  does not have any artifacts

### ISSUE THREAD

**Issue by MCOfficer** [univrsal/tuna#107]
As far as i can see, the only way to actually get 1.5.4 is to build it manually. Needless to say that's a no-go for most users.

Edit: whoops, bug label got assigned because i chose that issue template. My mistake.

**Comment by univrsal** [comment]
I haven't released the version on the obs forums, because something got in the way, that's why there's no binaries for it. You can get them under [github actions](https://github.com/univrsal/tuna/actions) if you really want the latest build.

**Comment by MCOfficer** [comment]
Unfortunately that's only an option with a github account, so I can't use those links for the AUR package. I will be waiting for the release, thank you :)
