### ISSUE TITLE
Web Browser Source not working 

### ISSUE THREAD

**Issue by Israax** [univrsal/tuna#108]
I'm trying to use tuna to display sound cloud info.
I have tampermonkey and the script installed, and the script is running (sorry for french) :
![image](https://user-images.githubusercontent.com/29656781/104529194-70accf80-5609-11eb-974d-5e71d77d2278.png)

My tuna settings are as follow :
![image](https://user-images.githubusercontent.com/29656781/104529234-8cb07100-5609-11eb-94a4-70b17c3f73f8.png)
but no soung info is showing on the text files.

And I also have this weird issue when adding song info outputs : 
![image](https://user-images.githubusercontent.com/29656781/104529313-b9648880-5609-11eb-818d-73e8b5c66308.png)

(sorry if I'm doing this request very wrong but I cannot find a solution)

**Comment by univrsal** [comment]
enter localhost:1609 and post what it says (if it's complaining about an insecure connection you can ignore that)

**Comment by Israax** [comment]
{
    "status": "unknown"
}

**Comment by univrsal** [comment]
Change the port to 1608. The script uses 1608 and needs to be edited if you want to use a different port.

**Comment by Israax** [comment]
I got the same thing : 
![image](https://user-images.githubusercontent.com/29656781/104582995-dd9f8400-5660-11eb-8c0b-a2521dfb99f2.png)

**Comment by Israax** [comment]
![image](https://user-images.githubusercontent.com/29656781/104583026-e98b4600-5660-11eb-8c1d-79bd2ccac2ff.png)

**Comment by Israax** [comment]
I dont know if it helps but it doesn't work on spotify webplayer as well

**Comment by univrsal** [comment]
Spotify broke apparently, but soundcloud works. The last thing you can do is open the developers tool (F12) and look at the console

**Comment by Israax** [comment]
got a lot of error : 
![image](https://user-images.githubusercontent.com/29656781/104660116-3bb28280-56c6-11eb-9413-1a29f2001a3b.png)

**Comment by Israax** [comment]
okey googled a little and disabled my addblockers, now I have those errors :
![image](https://user-images.githubusercontent.com/29656781/104660614-34d83f80-56c7-11eb-91b1-6f939aa4ce30.png)
![image](https://user-images.githubusercontent.com/29656781/104660635-3efa3e00-56c7-11eb-97f3-61f06481bd71.png)

**Comment by univrsal** [comment]
Yeah that one's broken, but for spotify you should just use the spotify source in the plugin.

**Comment by Israax** [comment]
thanks a lot for the help, and thanks for creating this amazing plugin !

**Comment by jadelabe** [comment]
Is there any plan on fixing the spotify web source?, I managed to get some info on the server by adding the uuid at the end of the query for progress and duration, The script is no longer throwing any errors, but im only seeing this

{
    "status": "playing",
    "title": "I'm Still Standing"
}

**Comment by univrsal** [comment]
You should use the native spotify source as it's more reliable
