### ISSUE TITLE
Soundcloud is not working with tampermonkey script running

### ISSUE THREAD

**Issue by timwillhack** [univrsal/tuna#109]
It used to work but now it doesn't seem to be (after working for a couple weeks)

1. Open soundcloud in chrome
2. Play music
3. check in obs that the tuna plugin is running (check)
4. None of the sources linked to my tuna files are updating
![image](https://user-images.githubusercontent.com/582984/104933551-0ed8c680-5977-11eb-9bfa-5143a8d49b90.png)

It says that the selected music source doesn't support the option I specified (%t) so I don't know if something weird happened with the webbrowser based obs plugin

**Comment by jzgdev** [comment]
I'm also having this issue

**Comment by aaronius25** [comment]
Are you able to use soundcloud now?

**Comment by vvouivre** [comment]
Also having this issue with not only SoundCloud but also Spotify. I do not use the app version of Spotify because it's a ram hog.  😓

**Comment by univrsal** [comment]
Soundcloud works again, I'll make a release later. Spotify doesn't but you should use the integrated spotify source for that.
