### ISSUE TITLE
Song format 'A' at the beginning of a line gets replaced

### ISSUE THREAD

**Issue by pkej** [univrsal/tuna#11]
I wanted to have the following as my song format in the text file:

Album: %a %bTitle: %t %bArtist: %m
But the A without a % in front gets parsed as %A and gets an uppercase album name in the output.

Instead I used this:
%b Album: %a %b Title: %t %b Artist: %m

Which adds extra spaces, but at least works. I had to add spaces on all lines for alignment purposes.

**Comment by univrsal** [comment]
Seems there was a bug with the formatting. It splits the string at the '%' and removes them, which works for all splits, except the first one. f583d36a003a23a1f455e832bbf201ff6b2cc26f should fix it
