### ISSUE TITLE
not able to install on debian 10

### ISSUE THREAD

**Issue by oddsoul** [univrsal/tuna#110]
have tried to extract and place in "plugins" folder but OBS crashes and refuses to open when tuna is in plugins folder

**Comment by univrsal** [comment]
you'll probably have to compile it yourself. Only Ubuntu 20.04 is officially supported as that's what's used to compile the plugin. And  debian is known to have ancient packages, so that's most likely where the problem is coming from.

**Comment by oddsoul** [comment]
Tried to compile but end up with following: 

oddsoul@Shedbox:~/Desktop/tuna/tuna$ mkdir build && cd build
oddsoul@Shedbox:~/Desktop/tuna/tuna/build$ cmake ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at deps/CMakeLists.txt:16 (include):
  include could not find load file:

    taglib/ConfigureChecks.cmake


-- Looking for strndup
-- Looking for strndup - found
-- Looking for getaddrinfo
-- Looking for getaddrinfo - found
CMake Error: File /home/oddsoul/Desktop/tuna/tuna/deps/libmpdclient/include/mpd/version.h.in does not exist.
CMake Error at deps/CMakeLists.txt:21 (configure_file):
  configure_file Problem configuring file


CMake Error: File /home/oddsoul/Desktop/tuna/tuna/deps/taglib/taglib/taglib_config.h.cmake does not exist.
CMake Error at deps/CMakeLists.txt:25 (configure_file):
  configure_file Problem configuring file


CMake Error: File /home/oddsoul/Desktop/tuna/tuna/deps/taglib/config.h.cmake does not exist.
CMake Error at deps/CMakeLists.txt:27 (configure_file):
  configure_file Problem configuring file


-- Found Libcurl: /usr/lib/x86_64-linux-gnu/libcurl.so  
CMake Warning at CMakeLists.txt:60 (message):
  Missing Spotify API info


CMake Warning at CMakeLists.txt:65 (message):
  Missing Last.fm API info


-- /home/oddsoul/Desktop/tuna/tuna/deps/mongoose/mongoose.c
-- Configuring incomplete, errors occurred!
See also "/home/oddsoul/Desktop/tuna/tuna/build/CMakeFiles/CMakeOutput.log".

**Comment by univrsal** [comment]
you need to clone with submodules: ``git clone https://github.com/univrsal/tuna --recursive``. Keep in mind that by default last.fm and spotify API keys are set to missing, which means that they will not work unless you provide them with your own.
