### ISSUE TITLE
[MPD] Covers not displaying with umlauts in path

### ISSUE THREAD

**Issue by lhaus** [univrsal/tuna#111]
**Describe the bug**
Covers are missing (grey question mark) for all songs that contain umlauts (and likely other special chars) (e.g. `C:\Users\lhaus\Desktop\Music\Röyksopp`)

**To Reproduce**
1. Play file with [äöü] in path

**Expected behavior**
The cover being displayed

**Log**
https://obsproject.com/logs/giBjGibi9aHGK3fq

**Additional info**
OS: Windows 10 20H2

**Comment by univrsal** [comment]
Can you test the nightly builds from [here](https://github.com/univrsal/tuna/actions/runs/507319263)?

**Comment by lhaus** [comment]
@univrsal Heya, thanks for taking a look at this!

I just installed the latest nightly build, and I'm afraid the same issue is still there.

Screenshot: https://img.zotan.services/i/56195cf19b8ad49097258d3d891afd6b606d4e72b32c8e7ec3156cf0e27ad8a2.png

Laura

**Comment by univrsal** [comment]
It was another case of Windows can't handle UTF8. Should be fixed now.

**Comment by lhaus** [comment]
Working now, thank you!
