### ISSUE TITLE
Crash on startup with VLC sources (1.5.4)

### ISSUE THREAD

**Issue by ZeAntwan** [univrsal/tuna#112]
**Describe the bug**
When opening OBS, a crash alerts shows while OBS appears behind "working".

On Windows with OBS 26.1.1 using the 1.5.4 nightly build

**To Reproduce**
1. Have a scene whit a VLC audio Source active
2. Set Tuna to use this VLC Source
3. Close the program
4. Open it back up

**Expected behavior**
OBS Not Crashing

**Screenshots**

**Log**
[Crash log](https://obsproject.com/logs/RxLrfQjMXSxhFqS2)

**Additional context**
I've had for a long time the same bug as mentionned here https://github.com/univrsal/tuna/issues/95. I did a full Windows wipe and clean reinstall of OBS, but the problem always comes back

**Comment by univrsal** [comment]
I can't replicate this, can you try [this](https://github.com/univrsal/tuna/actions/runs/507752721) nightly?

**Comment by ZeAntwan** [comment]
No more crashes! It seems to have worked! I'll update you if it comes back (it's kind of inconsistent)
