### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by streupdawg** [univrsal/tuna#113]
I am trying to install the Tuna plugin on OBS for us in a 24/7 audio stream on youtube. I am using an Ohbubble server using windows ten, and have tried multiple ways of installing the plugin using both the installer and manually drag and dropping the files into the folders, when I open OBS in the tool setting there are no tuna settings and no Tuna options. Not sure if this is a bug, but I could really use some help. Thanks in advance.

**Comment by univrsal** [comment]
You're most likely missing the visual c++ distributables https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0
