### ISSUE TITLE
Transparent Album cover and Refresh time low?

### ISSUE THREAD

**Issue by Monkkami** [univrsal/tuna#115]
First of all, I'm really enjoying this Widget so far!
But I would really like two features that I'm not even sure if are there and I'm just dumb.
1: The album cover PNG when not playing any song. I'd like it if it was transparent or just hidden.
 [example]
![Screenshot_1](https://user-images.githubusercontent.com/79019599/107857641-47fe3c80-6e38-11eb-8a20-d028f5770a4b.png)
2: Everything (except the progress bar) seems to be refreshing every 30 seconds or so. e.g. (The "Song progress", "Song title" etc.) 
So a new song could come in and take like 30 seconds to display the change.
I've changed the ms to the lowest value (500) but the problem remains.

Thanks in advance!

**Comment by univrsal** [comment]
For the cover image you just need to replace the png file which is in the data folder of the plugin (``C:\Program Files\obs-studio\data\obs-plugins\tuna`` or something). Are you using Spotify as the source? If so then it's Spotify limiting the requests, you'll have to register your own app as decribed [here](https://www.youtube.com/watch?v=Z0S430tm5ZI)

**Comment by Monkkami** [comment]
Thanks a lot! Previously I tried to change the PNG in C:\Users\{user} instead which got replaced instantly, I'm a noob. ^^
About the refresh delay, is there a fix? Or is that on my end?

**Comment by Monkkami** [comment]
Thanks a lot, both solutions worked!
