### ISSUE TITLE
spotify open login page

### ISSUE THREAD

**Issue by tricky30de** [univrsal/tuna#116]
Client ID and Client Secret have been importet to tuna.
The login gives me this response in the browser
INVALID_CLIENT: Invalid redirect URI

**Comment by univrsal** [comment]
did you set the redirect uri in the spotify developer dashboard?

**Comment by tricky30de** [comment]
how should I set it?

**Comment by tricky30de** [comment]
How should I set the redirect?

**Comment by univrsal** [comment]
It should be set like this
![Image](https://github.com/user-attachments/assets/6f994bfc-dfd4-410e-aedc-d83c9f025cc6)
