### ISSUE TITLE
Song Info Outputs disappear

### ISSUE THREAD

**Issue by locirecords** [univrsal/tuna#122]
Every time I open Tuna Settings and enter my Song Info Outputs correctly, then click apply and ok to close the window, they don't save. So if I reopen Tuna Settings they are gone and the box is empty.
This is preventing me from transmitting any info to a Text Source.

**Comment by univrsal** [comment]
I've updated the issue template, you can take a look at it here: https://github.com/univrsal/tuna/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
Please follow it.
