### ISSUE TITLE
Latest version of OBS/Spotify/Tuna doesn't capture artist on Spotify

### ISSUE THREAD

**Issue by MKiperszmid** [univrsal/tuna#124]
**Describe the bug**
Tuna should capture Artist name from Spotify, but it's capturing Song title instead 

**To Reproduce**
1. Just import the file that gets created once you install tuna. It shows SONGTITLE - SONGTITLE

**Expected behavior**
It should show SONGARTIST - SONGTITLE

**Screenshots**
![image](https://user-images.githubusercontent.com/16141845/113810356-71548e00-9740-11eb-8996-328e09be82a2.png)

**Log**
[Add the link to your obs studio log](https://obsproject.com/forum/threads/please-post-a-log-with-your-issue-heres-how.23074/)
https://obsproject.com/logs/taXAZs2qriFjENZ6

**Additional context**

**Comment by univrsal** [comment]
please update the plugin first and see if that fixes the issue

**Comment by MKiperszmid** [comment]
Latest build is 1.5.3 right? 1.5.4 only has source, not the actual folders and files to go in the plugins folder

**Comment by univrsal** [comment]
yes

**Comment by nemaides** [comment]
Just gonna add here that i have the same issue.
Tried version 1.5.3 of Tuna on OBS 26.1.1, no artist is being captured.
The cover is saved just fine.
I tried logging in again and getting new tokens, but that didn't work.

**Comment by univrsal** [comment]
just to be clear %a is the album title not the artist

**Comment by nemaides** [comment]
> just to be clear %a is the album title not the artist

I meant album.. facepalm..

Then again, i just noticed i'm not getting either album nor song title. like that whole song info output deal isn't working..
Gonna try and redo everything on my end..
