### ISSUE TITLE
Ability to set a refresh rate lower than 500ms

### ISSUE THREAD

**Issue by Daksh777** [univrsal/tuna#126]
Currently, it doesn't seem to go lower than 500ms but I'd like to set around 100-200ms, is it possible?

**Comment by univrsal** [comment]
depends on what music source. But I generally don't see a reason for it

**Comment by Daksh777** [comment]
> depends on the music source. But I generally don't see a reason for it

I'm using Spotify as a source.
I'm streaming music on YouTube so I'd like that the refresh rate could be lowered because I don't quite like when the audio is being played and the metadata is fetched with a delay.

**Comment by univrsal** [comment]
So you want to send a request to the spotify servers ten times a second? Are you using your own Client id and secret? Because if not then you're most likely just getting rate limited. 500 milliseconds should be more than enough, but it won't do much if Spotify is just rejecting the requests.

**Comment by Daksh777** [comment]
I'm using the authentication code, token and refresh token. Will anything less than 500ms get me rate limited?

**Comment by univrsal** [comment]
Spotify decides when to limit the requests. You are sharing a client id with everyone else, so if too many people use the spotify integration it'll get slowed down. To work around this you have to register your own [Spotify App](https://www.youtube.com/watch?v=Z0S430tm5ZI).

**Comment by Daksh777** [comment]
So if I use a Spotify app, can the refresh rate restriction be lowered/removed?

**Comment by univrsal** [comment]
There's no reason for it, because 500 miliseconds is more than fast enough. You're currently not getting 500 miliseconds because Spotify is rejecting the requests

**Comment by Daksh777** [comment]
Got it, but I also use window titles, can I reduce the refresh rate for it?

**Comment by univrsal** [comment]
Nope, even if you could obs studio doesn't refresh text and image files that fast.

**Comment by Daksh777** [comment]
Oh, alright. Thanks for the explanation.
