### ISSUE TITLE
VLC option wont allow me to select a source

### ISSUE THREAD

**Issue by josh-65** [univrsal/tuna#127]
**Describe the bug**
When I try they all show up but selecting one will just put it back to none.

**Expected behaviour**
When I select a VLC source to use it should stay on it

**Log**
[OBS log.txt](https://github.com/univrsal/tuna/files/6446756/OBS.log.txt)

**Comment by Neo-Desktop** [comment]
I ran into this issue as well, stopping tuna first, before making changes, works for me

**Comment by josh-65** [comment]
That worked thanks
