### ISSUE TITLE
feature request: tidal integration

### ISSUE THREAD

**Issue by mia-cx** [univrsal/tuna#129]
i use tidal to play music, right now i have to get the song information for this plugin through last fm, but tidal does have an api which would make it possible to do this in the plugin.

**Comment by univrsal** [comment]
Tidal does not have an official API and unofficial API's cannot retrieve information about the currently playing song. Unless you can point me to documentation that says otherwise this can't be added until Tidal adds an official API.

**Comment by Veri7ion** [comment]
[TidaLuna](https://github.com/Inrixia/TidaLuna) has a [plugin](https://github.com/vMohammad24/luna-plugins/tree/master/plugins/api) that creates an API.

Would it be possible to add TIDAL integration using this API?

**Comment by warmbo** [comment]
I would also love this!
