### ISSUE TITLE
OBS exits after requesting token for Spotify

### ISSUE THREAD

**Issue by evilarceus** [univrsal/tuna#131]
**Describe the bug**
After going through the process to use Spotify with Tuna, OBS exits after pressing the "Request token" button.

**To Reproduce**
1. Open Tuna settings and go to the Spotify tab
2. Press "Open login page" and authenticate Tuna
3. Copy and paste the authentication code into the authentication code field in OBS
4. Press "Request token"

**Expected behavior**
OBS does not exit and it successfully gets a token.

**Screenshots**
https://user-images.githubusercontent.com/1747088/120571517-26b56200-c3cf-11eb-8a86-85c98ff9ae94.mp4

**Log**
[https://obsproject.com/logs/gXSDzQPvKy24jU9-](https://obsproject.com/logs/gXSDzQPvKy24jU9-)

**Additional context**
This bug occurs in OBS 26 and 27 when using the latest stable and nightly builds of Tuna.
There are no logs in the `crashes` directory.

**Comment by Tipyx** [comment]
I experienced this too after a clean reinstall of OBS on a new PC

**Comment by Glazami** [comment]
This only happens to me with last.fm.
Also, the cover does not load in last.fm, and when the settings are applied, obs hangs and crashes

**Comment by vvouivre** [comment]
This happens to me too.

**Comment by NichtFireTV** [comment]
Smae here

**Comment by mdsitton** [comment]
Same here

**Comment by mdsitton** [comment]
Here's the entry from my OBS log file:

`13:32:19.882: [tuna] Spotify response: {
13:32:19.882:     "access_token": null,
13:32:19.882:     "error": "invalid_grant",
13:32:19.882:     "error_description": "Invalid authorization code",
13:32:19.882:     "refresh_token": null
13:32:19.882: }
13:32:19.882: 
13:32:19.882: [tuna] Couldn't parse json response!`

**Comment by univrsal** [comment]
I'm fairly certain this is caused by some changes I made to fix #89

**Comment by univrsal** [comment]
Can you try [this](https://github.com/univrsal/tuna/actions/runs/922726380) build (provided the pipline isn't broken again) and see if the issue is fixed?

**Comment by mb-techcash** [comment]
Hi, I am also having this problem. I tried at least 4 different releases, and none seem to work. I can't get VLC to work as a source either. Any help is appreciated, just wanna stream some tunes on linux

**Comment by univrsal** [comment]
I definitely tried the fix on linux and it worked

**Comment by vvouivre** [comment]
i just tried this fix and it works on my most recently updated windows PC, thanks a lot! i appreciate it very much!

**Comment by Tipyx** [comment]
Worked too on Windows PC, thanks @univrsal ! (for the fix and the hard work <3)
