### ISSUE TITLE
Tuna webservice not answering requests

### ISSUE THREAD

**Issue by tvvmongeek** [univrsal/tuna#132]
**Describe the bug**
Tuna server on port 1608 does not answer at all

**To Reproduce**
1. Configure Tuna to listen on port 1608
2. Attempt a connection to port 1608 (either with browser, curl, tampermonkey script...)

**Expected behavior**
Tuna should send back a response, even if invalid data is sent/requested

**Log**
https://obsproject.com/logs/iUfa4RPiPoE73crq

**Additional context**
Tried with OBS 26 and 27, same result
I see an obs64.exe listening on defined port (tried with different ports just in case)
Same behaviour with OBS running in administrator mode

Here is a curl -v request log : 

```
curl -v http://127.0.0.1:1608
* Rebuilt URL to: http://127.0.0.1:1608/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 1608 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:1608
> User-Agent: curl/7.52.1
> Accept: */*
>
```

It stays at this point without going further.

**Comment by univrsal** [comment]
Should be fixed

**Comment by tvvmongeek** [comment]
Hi !
Sorry but the latest release is the one i installed and i have the issue with.
Do i need to compile the repo current code to fix the issue in my setup ?

Best regards

**Comment by univrsal** [comment]
https://github.com/univrsal/tuna/actions/runs/922937643 contains the fix

**Comment by tvvmongeek** [comment]
Hello,

I can confirm it works great now with the fix you pushed.

Thank you very much !

Best regards
