### ISSUE TITLE
Tuna process does not run in release 1.5.4

### ISSUE THREAD

**Issue by julienFL** [univrsal/tuna#133]
Using OBS v27.0.0 64-bit on Windows 10 Pro, the Tuna process does not seem to run with the release 1.5.4, despite the status in Tuna's settings displaying "Tuna is running".

I have enabled the option "Host/receive information on local webserver with port: 1608", but by connecting to http://localhost:1608 in a web browser, nothing shows up.

The logs do not contain any error and there is no crash report.

Switching to Tuna release 1.5.3 fixes the issue

**Comment by univrsal** [comment]
this has already been fixed, I just haven't made a release yet
