### ISSUE TITLE
Refreshing Spotify Auth crashes OBS Studio

### ISSUE THREAD

**Issue by adbakke** [univrsal/tuna#135]
OBS Crashes on attempting to refresh Spotify Authentication.

1. Open Tuna menu from OBS Tools menu item
2. Click the spotify login button
3. Copy new auth token
4. insert new auth token from website that opened
5. Click button to get auth code.
6. Crash.

[OBS Log](https://obsproject.com/logs/rqqbSuwrr57KqJvG)

Also noticed the OBS plugin page says fixes were made for 27.0 but the downloads page only has builds from 2020.

**Comment by univrsal** [comment]
#131
