### ISSUE TITLE
OBS Crashes when authenticating Spotify

### ISSUE THREAD

**Issue by MrJordilicious** [univrsal/tuna#137]
Recently I had to do a reinstall of OBS. When I went to install Tuna again, I noticed that everytime I tried to authenticate my Spotify, it crashed OBS. I can open the login page where I get the auth code, but when I try to paste the auth code and request a token, it crashes OBS.

I already tried reinstalling Tuna, but so far, that didn't help. I was always able to use it without issue, so I hope this can be resolved.
I uploaded a log file when the crash happens, which might shed some more light on it? https://obsproject.com/logs/y6mVGTZZYWYOj7Vy

**Comment by univrsal** [comment]
Update tuna
