### ISSUE TITLE
Feature Request: Transparent/Custom "No Song Playing" cover image

### ISSUE THREAD

**Issue by LividJava** [univrsal/tuna#138]
Allow us to set a custom image when no music is playing.
Or optionally set the image to transparent when nothing is playing (but if no cover art is available display the question mark image)

This is to "hide" the graphic etc, when nothing is playing

**Comment by LividJava** [comment]
Edit to this, you can replace it in the plugin folder, but this is not apparent to the end user

**Comment by univrsal** [comment]
I'll just add it to the documentation, even though nobody reads that stuff anyways.
