### ISSUE TITLE
Can't Uninstall Mac

### ISSUE THREAD

**Issue by Xukkorz** [univrsal/tuna#141]
Software didn't work as expected and I want to uninstall the PKG on a Mac. The Pkg file doesn't have uninstall as an option so I'm not sure how to actually remove this program. Is there a list of what is put where on Mac?

**Comment by univrsal** [comment]
https://wincent.com/wiki/Uninstalling_packages_%28.pkg_files%29_on_Mac_OS_X 
idk, I don't use macs
