### ISSUE TITLE
File extensions are not removed in title

### ISSUE THREAD

**Issue by matbcvo** [univrsal/tuna#143]
**Describe the bug**
Tuna is still writing full title (%t) with file extension into output text file when I have "Remove file extensions from title" checked.

Tuna v1.5.5
I'm using OBS with VLC Video Source.

**To Reproduce**
1. Tuna settings -> Check "Remove file extensions from title"
2. Add "%t" in Song info outputs
3. Read output text file

**Expected behavior**
When "Remove file extensions from title" is checked, then file extension should be removed from title in output file.

**Screenshots**
https://i.imgur.com/cT7jviS.png
https://i.imgur.com/lqvwkL3.png

**Log**
https://pastebin.com/raw/ePeYMqNk

**Comment by matbcvo** [comment]
https://github.com/univrsal/tuna/blob/master/src/util/utility.cpp#L208

I can see that some file extensions aren't listed. Maybe it would be better to read from file that contains list of file extensions? So everyone can modify that list.

Or second better variant: Read title, find last dot and strip it from there (file extension starts always with dot)

**Comment by Pkern-Starset** [comment]
Same here with v1.5.5, it's the same result on my side.

[Result (obs)](https://prnt.sc/1jlwmye)
![Config in Tuna and OBS](https://user-images.githubusercontent.com/37908544/128432099-c148d9d1-a2bd-4120-b868-2d126237f264.png)

**My Logs:**
[Logs from today](https://pastebin.com/raw/BWbQ6gsh)

Haven't found any useful information in the logs, but if i were not totally stupid while reading the code, i think the button just does nothing atm. I've never written cpp code so, don't blame me if i'm totally wrong here. 🤷‍♂️
I've also noticed that the checkbox isn't present on the dev-branch anymore, is the feature planned to be implemented in any form if not happened allready?

Nice Plugin btw! I really love tuna! ❤

**Comment by univrsal** [comment]
>Haven't found any useful information in the logs, but if i were not totally stupid while reading the code, i think the checkbox-value does nothing atm. I've never written cpp code so, don't blame me if i'm totally wrong here.

that is indeed correct I guess I just forgot to implement that part
