### ISSUE TITLE
Tuna doesn't apply variables to files

### ISSUE THREAD

**Issue by tonalaty** [univrsal/tuna#144]
Hello,

I'm using the web browser source with Deezer.

The plugin worked while a test 3 month ago.

But today, the plugin doesn't apply the variables in the destination files.
The plugin receive correctly all the song infos.
![image](https://user-images.githubusercontent.com/88514102/128424834-64090482-5860-4350-96ba-f0f084dccc12.png)

Only thing I see is this error showing now : 
![image](https://user-images.githubusercontent.com/88514102/128424978-1218ce1d-9f8e-4c97-9d44-e3fc674b0970.png)

I'm using Tuna v1.5.5 and the TamperMonkey script v1.0.5

**Comment by univrsal** [comment]
The playing state wasn't being retrieved correctly. Update the script and it should work again
