### ISSUE TITLE
VLC won't work to show

### ISSUE THREAD

**Issue by Dortimus51** [univrsal/tuna#15]
I can't use to show the VLC plugin's playing title. It shows: VLC support is disabled, either because OBS updated and it was disabled by the user, or because VLC isn't installed. VLC is installed and has a active source

**Comment by univrsal** [comment]
You should've gotten a message box asking you about whether you want to enable VLC support anyways. If not you can edit
```%appdata%\obs-studio\global.ini``` and set ```vlc.force.enable=true``` under the ```[tuna]``` region
