### ISSUE TITLE
Spotify Authorization Token problem

### ISSUE THREAD

**Issue by Glazami** [univrsal/tuna#150]
```
= 2021.09.16 16:47 =
{
    "error": "invalid_grant",
    "error_description": "Invalid authorization code"
}
```

After re-authorization and applying the authorization settings, it is enough for one track or until the tuna settings are closed. after that, the track update stops.

Or is it some kind of problem with the application of settings.

**Comment by Glazami** [comment]
After authorization and applying the settings, tuna responds with successful authorization and receiving an update and authorization token, but this is only enough for one track, when the track is changed, the update no longer occurs

**Comment by thebiblelover7** [comment]
@univrsal I have this same problem, it only gets the first track and no album art. Plus, this issue is not resolved yet, please *reopen* the issue.
