### ISSUE TITLE
Spotify Authorization code expired after apply or OK button and OBS Restart

### ISSUE THREAD

**Issue by chrispyni** [univrsal/tuna#153]
Spotify Authorization code expired after pressing Apply or OK button and OBS Restart!

Error:
```
{
    "error": "invalid_grant",
    "error_description": "Authorization code expired"
}
```

**Comment by FabienStG** [comment]
Hello, 

Same problem here, if you click on the Apply or Ok button of the Tuna Parameters windows, the status log turn from "Connected" to "Not connected"

https://obsproject.com/logs/w61xUU_ubFLKSjE6

But, it's still an amazing plugin and really thank you to make it work, even for my Mac !

**Comment by univrsal** [comment]
Update to the latest version

**Comment by FabienStG** [comment]
Thank you for the answer but Tuna is already up to the 1.6.
Still when I use the Apply or Ok, the status log turn change to Not Connected.
Everything work fine only if I keep the Tuna parameter windows open after requesting the token.
The log out do not appear in the Tuna log or the OBS logs

(I use my own Spotify app like you suggest, but It's the same issue with yours.)

**Comment by univrsal** [comment]
The latest version is 1.6.1

**Comment by FabienStG** [comment]
Thanks for the answer !
When I go to the releases page, the latest version seem to be the 1.6.
The 1.6.1 have only the source code to download but  no installer.

**Comment by univrsal** [comment]
Go to the obs resource page

**Comment by FabienStG** [comment]
Yeah, it’s up to date and completely work !
You’ve made my day ^^
Thanks again for all

Envoyé de mon iPhone
