### ISSUE TITLE
Spotify Login 

### ISSUE THREAD

**Issue by melodanino** [univrsal/tuna#160]
I accidentally logged into the wrong Spotify account and now I can't log out. 
Any help on how I can do the authenfication over again would be much appreciated. 
Thanks!

**Comment by univrsal** [comment]
You're gonna need to be a bit more specific with what exactly your issue is

**Comment by univrsal** [comment]
This doesn't seem to be related to the original issue. Please fill out a separate bug report and follow the issue template closely.

**Comment by melodanino** [comment]
> 
> 
> You're gonna need to be a bit more specific with what exactly your issue is

I logged into the wrong Spotify account when I was authorizing Tuna, and have no way of changing which account is linked. I was wondering if there was a way for me to authenticate it again but with a different Spotify account.

**Comment by melodanino** [comment]
Okay thanks a ton! I appreciate the quick response too!
