### ISSUE TITLE
Feature Request: Fade out after song changed

### ISSUE THREAD

**Issue by ikarycs** [univrsal/tuna#164]
Just a feature that will be cool to have.
make some type of event that allows to fade the sources after X amount of time, or make the fields blank such as when no song is being played (I use a blank png file).
thanks

**Comment by univrsal** [comment]
Tuna doesn't handle any of the song displaying, it uses text sources which are not capable of doing this kind of stuff. Tuna could probably hide/unhide the sources which in combination with hide/show transitions could make this work, but it's a bit tedious.
