### ISSUE TITLE
Last cover image remain even if the player is paused

### ISSUE THREAD

**Issue by Regnareb** [univrsal/tuna#17]
Right now when you pause Spotify the "Song Placeholder"is displayed but the cover image stays the same.
It would be handy to have the "Cover Placeholder" image displayed instead (or a transparent image but I guess the placeholder would be better for consistency).

**Comment by univrsal** [comment]
yeah that broke at somewhere in the last version, I'll try and fix it

**Comment by univrsal** [comment]
Fixed in 47a9dde7da71a9750e7b3eff93f731eefaa62fde
