### ISSUE TITLE
Deezer not working

### ISSUE THREAD

**Issue by userc479** [univrsal/tuna#177]
For the past few weeks Deezer suddenly stopped working on me and had been running it on latest OBS. 

However - Tuna has failed to work even with the following:
- Reinstalling Tuna Plugin
- Reinstalling TamperMonkey
- Reinstalling the script from GreasyFork for TamperMonkey
- Reinstalling OBS to recent latest version (hate myself.... I gotta do all the scenes, triggers and more all over again!)
- Downgrading OBS to version 29.
- Checked Google Chrome for update
- Install Firefox / Tuna script

And none of this has got Tuna reacting to Deezer - it will work for YouTube but not Deezer. Any help would be so much appreciated.

**Comment by kurzehosenmann** [comment]
I have the same Problem

**Comment by univrsal** [comment]
Update the user script and try again

**Comment by userc479** [comment]
WOOHOO! Thank you :)
