### ISSUE TITLE
Spotify showing "Paused" for all text info (except album cover)

### ISSUE THREAD

**Issue by lihuelworks** [univrsal/tuna#178]
**Describe the bug**
When trying to conenct spotify 

**To Reproduce**
0. (Tried on Tuna Player on version 1.9.7)
1. Connect tuna player plugin to spotify
2. Configured titles like so (paths are displayed as normal, I blurred them from the image)
![image](https://github.com/univrsal/tuna/assets/49965980/5a9e7001-274d-49d0-aa92-9d927c9a008b)
3. See result as "Paused" on Spotify no matter the field text chosen.
![image](https://github.com/univrsal/tuna/assets/49965980/86b3f55b-b95b-4796-b24c-e0a6022114ed)

**Expected behavior**
Seeing data from Spotify like title, artist, and so.

**Additional context**

**Comment by univrsal** [comment]
The requests to Spotify are timing out so it seems to be a connection issue. You can increase the in the spotify tab.

**Comment by lihuelworks** [comment]
Thank god it's a temporary issue, I was going crazy trying to figure out what it was. Just two things: 

1. Increase the what? It seems to have cut off there.
2. Off-topic, but where are the docs about how to control the progress bar? I've been looking for them for half an hour. Are they buried in one of the yt videos on the obs page?

**Comment by univrsal** [comment]
You can increase the time before a connection times out in the Spotify tab. The progress bar has no controls, it just shows the progress.

**Comment by lihuelworks** [comment]
Great, will try tomorrow to see if Spotify gets his stuff together or stills has timeout problems. Thanks for the info!

**Comment by lihuelworks** [comment]
Can confirm, if this happens again is a temporal Spotify timeout issue, as it now works as normal. If this happens to you over spotify, check for any timeouts on your OBS Log (Help > Log Files > View Current Log). Sadly the only option is wait for Spotify (or any other service) to work again.
