### ISSUE TITLE
Question: Using Window Title for foobar2000, any way I can send playback time and song duration to Tuna?

### ISSUE THREAD

**Issue by NafenX** [univrsal/tuna#179]
I'm using foobar2000 along with the YouTube Source plugin in order to play songs from YouTube in there, and I've formatted my foobar2000 Window Title so it will say " - - /" and was wondering if there is any way to send the playback time and song duration info to Tuna to use with the progress bar source etc.

As it stands, right now the Tuna text source will show the full title bar but what I am hoping for is to cut the playback time and song duration out of the title and have it be used in the progress bar source.

**Comment by NafenX** [comment]
I don't really know how to tag on here

**Comment by univrsal** [comment]
No, the window title source can only get the window title. If you want other information you'll have to use another source like spotify, vlc, mpd etc.
