### ISSUE TITLE
Remove file extension using the default widget contained in the tuna directory

### ISSUE THREAD

**Issue by jefflima1** [univrsal/tuna#181]
Hello, using the local web server, there is the widget file inside the tuna folder, it works as expected, but I would like to know if it is possible to remove the .mp3 file extension also in the image capture contained here

![sadad](https://github.com/univrsal/tuna/assets/106811319/dde51ce3-e5ff-4b0e-9a22-a87e2c237852)

Even checking this option, the file extension still appears.

![sadad](https://github.com/univrsal/tuna/assets/106811319/3a768d05-81f5-4b9b-98d5-ec50eb02f669)

Thank you

**Comment by univrsal** [comment]
Try these builds at the bottom
https://github.com/univrsal/tuna/actions/runs/8438455450
