### ISSUE TITLE
Unable to display file name properly

### ISSUE THREAD

**Issue by fu5502** [univrsal/tuna#182]
{file_name}  label  Unable to display file name properly  The version used is Tuna v1.9.7

｛file_name｝标签无法正确显示文件名。使用的版本为罪新Tuna v1.9.7  obs版本：30.1.1（64bit）

**Comment by fu5502** [comment]
是不能显示中文吗？

**Comment by univrsal** [comment]
`{file_name}` is only available for VLC Video source and MPD
