### ISSUE TITLE
issue title If this tool can support Media Playlist Source by CodeYan is even better

### ISSUE THREAD

**Issue by gcyzidane** [univrsal/tuna#183]
If this tool can support Media Playlist Source
by CodeYan is even better

**Comment by univrsal** [comment]
That would require the Media Playlist Source plugin to offer some kind of way of retrieving metadata like the VLC source does. You can ask the author, but from what I can tell it would require changes in the media source of OBS studio.

**Comment by Avasam** [comment]
Is the VLC source even available on Linux? I couldn't find anything.
AFAIK, there's no way on Linux to have a shuffled playlist from local files AND display the currently playing song on stream, all without having to have a 3rd party program open on the side. :/

**Comment by univrsal** [comment]
It should be but OBS has to be compiled with it enabled.
