### ISSUE TITLE
Deezer

### ISSUE THREAD

**Issue by userc479** [univrsal/tuna#188]
Tuna is not responding with Deezer

**Comment by univrsal** [comment]
Just tested ant it works fine.

**Comment by userc479** [comment]
hmmm why it's not working on my end....

**Comment by univrsal** [comment]
![image](https://github.com/univrsal/tuna/assets/8353672/90e8205a-9935-4bc6-b501-939f379d9382)

**Comment by userc479** [comment]
reinstalled the script from greasy fork, overwritten to newest lib, using obs 30.1.2 - works with youtube but just not with Deezer

**Comment by univrsal** [comment]
I don't update the version on greasyfork that frequently. The most up to date version is always in the repository because that's where others can submit changes to. Try installing it from here:
https://github.com/univrsal/tuna/raw/master/deps/tuna_browser.user.js

**Comment by userc479** [comment]
YOU FREAKIN' GENIUS! You only gone and fixed the issue again! THANK YOU!
