### ISSUE TITLE
Spotify Api not connecting

### ISSUE THREAD

**Issue by codecumkey** [univrsal/tuna#189]
**Describe the bug**
When setting up Tuna on obs windows, log returns "invalid_client"

**To Reproduce**
1. install tuna
2. go to spotify tab
3. click open log in page
4. copy token after logging in
5. paste into authentication code 
6. click request token
7. enable log
8. log prints 
```
= 2024.05.08 18:57 =
{
    "error": "invalid_client"
}
```

**Expected behavior**
spotify connects on tuna

**Screenshots**
![image](https://github.com/univrsal/tuna/assets/141218447/5a27fd26-7eb6-48f9-b653-90f3254197e8)

**Log**
https://obsproject.com/logs/7UwhBxFqE1np8UKF

**Additional context**
Log appears to say token is null even tho it is pasted in

**Comment by codecumkey** [comment]
works on [tuna v1.9.7](https://github.com/univrsal/tuna/releases/tag/v1.9.7)
broken on [tuna v1.9.8](https://github.com/univrsal/tuna/releases/tag/v1.9.8)

**Comment by iamzamn** [comment]
> works on [tuna v1.9.7](https://github.com/univrsal/tuna/releases/tag/v1.9.7) broken on [tuna v1.9.8](https://github.com/univrsal/tuna/releases/tag/v1.9.8)

Exactly the same for me.

**Comment by univrsal** [comment]
I forgot to define the API keys when updating the automatic builds. Try this build:
https://github.com/univrsal/tuna/actions/runs/8867708112/job/24346528077
(downloads are at the bottom)

**Comment by univrsal** [comment]
I'm fucking stupid. That's the wrong build... Try this one
https://github.com/univrsal/tuna/actions/runs/9031598142

**Comment by univrsal** [comment]
https://github.com/univrsal/tuna/actions/runs/9068179678 should fix the issue

**Comment by ktg5** [comment]
> https://github.com/univrsal/tuna/actions/runs/9068179678 should fix the issue

This build worked for me; had the same issue as OP.

**Comment by univrsal** [comment]
Alright, I'll make a new release, thanks for the testing.
