### ISSUE TITLE
Tuna shows media control cover art instead of vlc

### ISSUE THREAD

**Issue by Molenfeuer** [univrsal/tuna#193]
**Describe the bug**
When I play music using VLC, sometimes the cover art of a YouTube video (or other video playing in my FireFox) appears instead of the cover art of the song. But my "Music source" is set to VLC (view Screenshot 2)!

**Expected behavior**
Only the cover art of the actual song is displayed. No matter what happens in my browser!

**Screenshots**
![grafik](https://github.com/univrsal/tuna/assets/32037518/f4e97e03-7df6-4e81-82d8-a480a69102c7)
*Bug*

![grafik](https://github.com/univrsal/tuna/assets/32037518/96c6e35b-63fc-4bbb-8a4d-21db7a7593b7)
*Expected behavior*

![grafik](https://github.com/univrsal/tuna/assets/32037518/69b252e4-9316-44a9-a173-96d1797886c6)
*General Tuna Settings*

**Log**
[https://obsproject.com/logs/D9w92kik4VBziQek](https://obsproject.com/logs/D9w92kik4VBziQek)

**Comment by univrsal** [comment]
Try this build https://github.com/univrsal/tuna/actions/runs/9500798262

**Comment by Molenfeuer** [comment]
Okay, I'm live rn and test it :D Give me a few hours!

**Comment by Molenfeuer** [comment]
I think the bug is fixed! This problem does not occur anymore!
