### ISSUE TITLE
Module '../../obs-plugins/64bit/tuna.dll' not loaded

### ISSUE THREAD

**Issue by gl09025** [univrsal/tuna#194]
OBS couldn't load tuna

[2024-07-01 22-38-30.txt](https://github.com/user-attachments/files/16054573/2024-07-01.22-38-30.txt)

**Comment by gl09025** [comment]
solve use the lastest obs

**Comment by LhymeFruit** [comment]
reviving because i have the exact same issue and im on the latest obs
