### ISSUE TITLE
The installer version on Windows is not working.

### ISSUE THREAD

**Issue by rust-floppy** [univrsal/tuna#195]
There is no log/crash/error log.
I spent about an hour testing this bug (as a fellow developer and tester, who appreciates your work), when I noticed that nothing changes in the OBS folder after a Tuna install, if the OBS is not in the default location.

Tuna installs to `C:\ProgramFiles\obs-studio`, regardless of the actual OBS installation location, and does not appear in the OBS tools menu.

**Repro**:

1. Install OBS to a different drive (if default is `C:\ProgramFiles\`, install it to `D:\twitch_stuff\` )
2. Download the latest Tuna installer for windows
3. Run the installer
4. Start up OBS from the location you installed it to (`D`)

Now you see that Tuna is not appearing at all in the tools.
But now, a folder named "`obs-studio`" with the Tuna files is created in` C:\ProgramFiles\` even tho OBS is installed on a different drive (`D`).

I'd suggest allowing the users _to specify the installation directory_.

I only tested _installing on a different drive_, not _on the same drive but in different folder_, but I'll leave that to you for now.

I hope I helped, and you can fix this unlucky bug soon!
If you need more information, I'll try to reply as soon as I can.

**Tuna**: Tuna v1.9.9
**OBS**: 30.1.2

Take care!

**Comment by univrsal** [comment]
This seems to be an issue on your end. I just uninstalled and reinstalled obs on the D:\ drive and the installer detected the new location automatically and the installation succeeded.
![image](https://github.com/univrsal/tuna/assets/8353672/0fb8dfae-9ab3-4130-8975-ef1c34762adf)

The installer is created via the obs plugin template so it's also not really something I have anything to do with.
