### ISSUE TITLE
Get Specify Process Windows Title [Feature Request]

### ISSUE THREAD

**Issue by shugen002** [univrsal/tuna#20]
For most of user of windows title , they may know which process is their music player . If we can set a process name , it will be more accurate to get music name from the Windows Title .
(a list of process name is better).

**Comment by univrsal** [comment]
I've taken a look at this now and went with the executable path, because the process id is something that is assigned at launch of the program and will differ every time making, which would mean that the user has to reset the process id every time the player is restarted.

**Comment by univrsal** [comment]
I've implemented this with 24d751cf3e8fe16716465e91b176aebad8c68d5a and will make a new release shortly, so you can test the feature. I haven't tested it on windows but it did seem to work on linux.
