### ISSUE TITLE
tuna UI elements broken & mpris not functional  

### ISSUE THREAD

**Issue by MNS26** [univrsal/tuna#203]
**Describe the bug**
> All UI elements dont show names, mpris not working despite it showing up correctly under the tab

**To Reproduce**
1. download plguin from github
2. extract files to OBS plugin folder
3. launch OBS 

**Expected behavior**
> UI elements having a propper name, dock working

**Screenshots**
> UI
![image](https://github.com/user-attachments/assets/8ef81b76-ff50-43a7-bca9-e651b6d216a1)
![image](https://github.com/user-attachments/assets/65d46d20-ceb8-436e-ae4a-fce7b4708c6f)
![image](https://github.com/user-attachments/assets/3726f0d8-6d34-46f2-abc2-59e8de5483a6)

adding anything to the song info list
![image](https://github.com/user-attachments/assets/caf8f87a-a9bb-4b88-a1a3-732fd8c56822)

tuna dock empty
![image](https://github.com/user-attachments/assets/e6c83a74-55ce-46da-9e7f-c3133d9821f7)

**Log**
[Add the link to your **entire** obs studio log](https://obsproject.com/forum/threads/please-post-a-log-with-your-issue-heres-how.23074/)
> https://obsproject.com/logs/5B1OBM2DWmSj9jlH

**Additional context**
> System: 
Operating System: Fedora Linux 40
KDE Plasma Version: 6.2.2
KDE Frameworks Version: 6.7.0
Qt Version: 6.7.2
Kernel Version: 6.11.6-200.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 10 × AMD Ryzen 5 7600X 6-Core Processor
Memory: 24.4 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7D77
System Version: 1.0

> having a basic install guide would also be VERY helpfull. (found the steps for arch in the issues)

**Comment by MNS26** [comment]
KdeConnect does send the current active media stream 
![image](https://github.com/user-attachments/assets/1122424e-d44b-4701-87f3-a1bb635b1579)

**Comment by univrsal** [comment]
You're missing the localization files. As for MPRIS I can't say anything about kde connect but firefox works just fine for me.

**Comment by MNS26** [comment]
![image](https://github.com/user-attachments/assets/54f6bc22-c650-4e6b-9ccf-17f288dab012)
are those the localization files?

**Comment by MNS26** [comment]
ok fixed the localization... missed the data folder `tuna/data/locale`

would you also mind adding a note for the build commands to the readme? i had quite a struggle finding the commands.

**Comment by univrsal** [comment]
The song path works the same way for all sources, see https://obsproject.com/forum/resources/tuna.843/

Building is basically just 
```
cmake --preset=linux-x86_64 -GNinja && cmake --preset=linux-x86_64 --build
```
or 
```
cmake --preset=linux-x86_64 -GNinja -DLOCAL_INSTALLATION=ON && cmake --preset=linux-x86_64 --build
```
to automatically install it into ~/.config/obs-studio/plugins.

**Comment by MNS26** [comment]
oh cool KdeConnect works too
![image](https://github.com/user-attachments/assets/8dd74f47-adb1-4bd5-8762-2a37437e608f)

i just had to manually tell it to use kdeconnect
and make kdeconnect not randomize its name for every event it sends

**Comment by MNS26** [comment]
> The song path works the same way for all sources, see https://obsproject.com/forum/resources/tuna.843/
> 
> Building is basically just
> 
> ```
> cmake --preset=linux-x86_64 -GNinja && cmake --preset=linux-x86_64 --build
> ```
> 
> or
> 
> ```
> cmake --preset=linux-x86_64 -GNinja -DLOCAL_INSTALLATION=ON && cmake --preset=linux-x86_64 --build
> ```
> 
> to automatically install it into ~/.config/obs-studio/plugins.

ah i see... i didnt know it could do local install on its own

**Comment by MNS26** [comment]
![image](https://github.com/user-attachments/assets/e4ec79ea-70b7-43db-b41b-978af76b06c2)
oh interesting it says its not available over MPRIS while its there (will look into that and make a PR if i get it working)

will close the issue now that tuna is working
