### ISSUE TITLE
Tuna - Web Browser - Not being picked up

### ISSUE THREAD

**Issue by userc479** [univrsal/tuna#204]
Hi - just to report tuna not picking up the Web Browser - it may pick up other things but I use deezer - I've checked within the tampermonkey script / got latest from here as advised on greasemonkey - but to no avail - help - got a special stream tomorrow and would like people to know what's being played.

**Comment by univrsal** [comment]
deezer should be working again with the newest version of the user script

**Comment by userc479** [comment]
Thank you so so much - you're doing a great job with keeping up to date with all the changes and responding efficiently :)
