### ISSUE TITLE
Cover Art won't display

### ISSUE THREAD

**Issue by Medotmedotcom** [univrsal/tuna#21]
Tuna has been great thus far, however, for some reason it refuses to write the cover art file to location for only 3 out of the hundreds of songs ive been able to play and see art for. 

Ive tried restarting, redownloading, changing file location.  VLC plays and recognizes the cover art. I even ran these tracks through tuna on a separate computer and it worked there. Nothing seems to get tuna to recognize this particular cover art on my primary pc.

**Comment by univrsal** [comment]
What file format are the songs?

**Comment by Medotmedotcom** [comment]
weve tried all different formats. primarily .alac . Of the computers, the computer where the cover wont write is PC, the other where it works is a Mac. 
These three songs are the only ones that wont work. is there something i can tell the person who made the files?

**Comment by univrsal** [comment]
You can take a look at the file tags with something like [mp3tag](https://www.mp3tag.de/en/index.html) and see if the cover is included there. I've never heard of alac so maybe you can convert it to something more common like flac or mp3

**Comment by univrsal** [comment]
I'll close this now and post updates in #38
