### ISSUE TITLE
Dock does not work with Spotify Premium

### ISSUE THREAD

**Issue by COOLIGUAY** [univrsal/tuna#22]
I'm trying with spotify premium and can't control the music from the dock.
The song title is displayed correctly.

With VLC the dock works fine.

And... should the volume bar be shown with spotify or VLC?

![image](https://user-images.githubusercontent.com/55640387/79078270-881bfc80-7d07-11ea-886e-4be9f2a47975.png)

**Comment by univrsal** [comment]
Can you give me the log file when you try to use the buttons?
![log](https://user-images.githubusercontent.com/8353672/79078849-c5c65880-7cfa-11ea-8ead-7c672660e216.png)

**Comment by COOLIGUAY** [comment]
https://obsproject.com/logs/iimR70FWDXstlYZG

In the log shows invalid token, but it's logged.

![image](https://user-images.githubusercontent.com/55640387/79079866-e0f09280-7d11-11ea-8280-a9f7b9281c98.png)

I have requested the token again and it shows the same.

**Comment by univrsal** [comment]
Can you try logging in again? Meaning click on open login page and then paste the new authentication code and press request token.
Changing the playback and volume requires special permissions, which should be granted when you login, but maybe they get lost once the token has to be refreshed, which would be strange.

**Comment by COOLIGUAY** [comment]
I just tried 2 more times with a new token and remains the same.

https://obsproject.com/logs/Thx1M7GZJIFrJjAw

**Comment by univrsal** [comment]
I might have found out what the issue is, I'll try and fix it and give you a test build

**Comment by univrsal** [comment]
Alright I fixed it. Also the volume isn't showing because implementing the volume for spotify is a bit of a hassle.

**Comment by COOLIGUAY** [comment]
Nice! I will wait for the next release to try again.
This is one of my favorites plugins.

**Comment by Bmille916** [comment]
I seem to have an issue similar. Had troubles logging in. Finally after a few attempts looking at the log it seemed to work. But the real issue is the Music control buttons don't work. I thought i saw somewhere something about Visual C++, but i also downloaded a bunch of plugins.

**Comment by univrsal** [comment]
I have fixed it, but I haven't made a new release yet

**Comment by univrsal** [comment]
I have nightly builds working, so anyone who wants can try them out by going to the [actions](https://github.com/univrsal/tuna/actions) then clicking on the latest run and then downloading the artifacts for your OS. Please try them and report back if you still have issues. Keep in mind that currently Tuna sometimes has to wait for the Spotify API because it only allows a certain amount of requests. If you have issues please post the log.

**Comment by COOLIGUAY** [comment]
I've tried the last nightly.

With VLC works fine, volume controls, track name or name of the file, etc.

Spotify can't log in, i've tried a few times in the last 4 hours.
I have left empty "Spotify client ID" and "Spotify client secret", authentication code only.

https://obsproject.com/logs/-3D9nzBxZK7B51Gk

**Comment by univrsal** [comment]
I'll give it a shot on windows, it seems to work just fine on linux though.

**Comment by univrsal** [comment]
Made a new nightly, logging in should work now again

**Comment by COOLIGUAY** [comment]
Great! Logged without problems in Windows 10.
At least with Spotify Premium i can't use the controls (previous, play/pause and forward).

Play/pause works occasionally if you click many times.

**Comment by univrsal** [comment]
As I said before the Spotify API limits the amount of requests, so if you want it to be more responsive you'll need to register your own Spotify app and provide tuna with the secret and id.
