### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by LitjFoxn** [univrsal/tuna#23]
I'm trying to install the install-mac.sh, but after pressing "y" to delete old version, I get prompted that there is No Such File or Directory when it tries to move the files over into the obs-studio plugin folder...

**Comment by univrsal** [comment]
Whats the exact output?

**Comment by LitjFoxn** [comment]
Deleting /Users/litjfoxn/Library/Application Support/obs-studio/plugins/tuna, is this ok? [y/N] y

Deleting...
Creating plugin folder
Moving plugin over
mv: rename tuna to /Users/litjfoxn/Library/Application Support/obs-studio/plugins/tuna: No such file or directory
Done!

**Comment by univrsal** [comment]
is there a "tuna" folder where the install script is located and does the folder /Users/litjfoxn/Library/Application Support/obs-studio/plugins/ exist?

**Comment by LitjFoxn** [comment]
I have tried moving the install script around in various folders out of the zip file, and also make delete the plugins folder (which originally was there), but with no luck.

**Comment by univrsal** [comment]
As long as you extract everything out of the release zip file you should be good

**Comment by chezedog** [comment]
Same issue here.

> is there a "tuna" folder where the install script is located and does the folder /Users/litjfoxn/Library/Application Support/obs-studio/plugins/ exist?

There is a "tuna" folder, and the "plugins" folder exists.
Even if you manually move the files over, the plugin is still missing from the "tools" menu in OBS

**Comment by univrsal** [comment]
Then I need your log
![ss](https://user-images.githubusercontent.com/8353672/79078849-c5c65880-7cfa-11ea-8ead-7c672660e216.png)

**Comment by chezedog** [comment]
I have uploaded it, all right.

**Comment by univrsal** [comment]
Now all I need is the link

**Comment by chezedog** [comment]
Oops.  [https://obsproject.com/logs/g_GKaNmV2Hq7fKtD](https://obsproject.com/logs/g_GKaNmV2Hq7fKtD)

**Comment by univrsal** [comment]
You're using an outdated version of obs studio, which prevents the plugin from loading. I know that version 25 doesn't run on older macOS versions, but I can only support the latest one.

**Comment by blackdevil72** [comment]
Hello,

there is the same problem on the linux version of the install script and Tuna doesn't appear in OBS tool menu.

https://obsproject.com/logs/cUN7wnS0mctkCSm_

What I discovered is that the install script will create a "tuna" folder and then move the "tuna" folder from the archive into that folder : /path/tuna/tuna/bin/
Doing a manual install correct that.

And for tuna not working I haven't found anything yet.

**Comment by iMaJiNair** [comment]
I have version 25 OBS but the files don't exist in the directory

**Comment by iMaJiNair** [comment]
> I have version 25 OBS but the files don't exist in the directory

Installing dependencies
Uninstalling old plugin
rm: /home/**********/.config/obs-studio/plugins/tuna/: No such file or directory
Installing plugin
mkdir: /home/********/.config/obs-studio/plugins/tuna/: Operation not supported
mv: rename ./tuna to /home/**********/.config/obs-studio/plugins/tuna/: No such file or directory
(base) MJs-Macbook-Pro:~ **********$

**Comment by iMaJiNair** [comment]
> > I have version 25 OBS but the files don't exist in the directory
> 
> Installing dependencies
> Uninstalling old plugin
> rm: /home/**********/.config/obs-studio/plugins/tuna/: No such file or directory Installing plugin mkdir: /home/********/.config/obs-studio/plugins/tuna/: Operation not supported mv: rename ./tuna to /home/**********/.config/obs-studio/plugins/tuna/: No such file or directory
> (base) MJs-Macbook-Pro:~ **********$

1.4.2 doesn't have a Mac OS downloadable file while 1.4.1 does
just update the URL to get to the older version

**Comment by iMaJiNair** [comment]
(base) MJs-Macbook-Pro:~ ******$ /Users/******/Downloads/tuna/install-mac.sh 
Checking for brew..
Checking for libmpdclient...
libmpdclient is already installed
Checking for taglib...
taglib is already installed
Uninstalling old version
Deleting /Users/******/Library/Application Support/obs-studio/plugins/tuna, is this ok? [y/N] y

Deleting...
Creating plugin folder
Moving plugin over
mv: rename tuna to /Users/******/Library/Application Support/obs-studio/plugins/tuna: No such file or directory
Done!
(base) MJs-Macbook-Pro:~ ******$

**Comment by iMaJiNair** [comment]
1.4.2 doesn't have a Mac OS downloadable file while 1.4.1 does
just update the URL to get to the older version

**Comment by iMaJiNair** [comment]
Help, I don't know what to do!

(base) MJs-Macbook-Pro:~ *****$ /Users/*****/Downloads/tuna/install-mac.sh 
Checking for brew..
Checking for libmpdclient...
libmpdclient is already installed
Checking for taglib...
taglib is already installed
Uninstalling old version
Deleting /Users/*****/Library/Application Support/obs-studio/plugins/tuna, is this ok? [y/N] y

Deleting...
Creating plugin folder
Moving plugin over
mv: rename tuna to /Users/*****/Library/Application Support/obs-studio/plugins/tuna: No such file or directory
Done!
(base) MJs-Macbook-Pro:~ *****$

**Comment by iMaJiNair** [comment]
I am trying to self navigate and cannot find the application support folder within the library, seems to be the issue, how would you approach this?

**Comment by iMaJiNair** [comment]
After deleting the old folder, a new one is not created

**Comment by iMaJiNair** [comment]
I wound up fixing this by installing 1.4.0 through the desktop & terminal. Now to figure out how to use the plugin...

**Comment by univrsal** [comment]
version 1.4.2b should fix the installation script
