### ISSUE TITLE
[linux] Spotify login is not kept after closing OBS and not working

### ISSUE THREAD

**Issue by blackdevil72** [univrsal/tuna#24]
https://obsproject.com/logs/2SoDs2pnE0ZT-M87

as said in the title the spotify log in token is not kept between two OBS session.

Also the whole spotify thing is not working even when conected.

**Comment by blackdevil72** [comment]
So after some fidleling around I've found a weird solution.
Loging in spotify > request a token > refresh the token

without refreshing the token the spotify login would not stay after quiting obs after that it does.

after that I have been confronted to a lot of bugs. it seems that spotify sent back errors to tuna making it unstable and prone to crashing.

**Comment by univrsal** [comment]
well It'd help if you give me the log for those errors

**Comment by blackdevil72** [comment]
oopsie sorry I completly forgot to add them. here they are.

=> This one hapened after adding spotify login. OBS freezed I had to kill it.
https://paste.chapril.org/?1694b8348b649061#Dkpi5srqD6dr5YzrrE5wDNKhnKWReZ9yHibP7F9CMpdS

=> This one show spotify API error and crash soon after
https://paste.chapril.org/?2f86c731f78a8320#2KRkxx64pQvcLmuSBVrHMd9wYcu6pBNb5k8KLB61gym3

=> This one OBS freezed too and had to kill it too.
https://paste.chapril.org/?d0cf89885070dc63#EQbB8NEwev4GRrXMhLa44aCn9HwMJb7WCyLcrCP5DDEG

=> an other exemple of spotify API error
https://paste.chapril.org/?d613aa2804c59660#8dqRsZZ7wGpt59LxaAummGZgYHwvwuFv2E9fnPD46GpG

**Comment by univrsal** [comment]
I tested the latest [nightly](https://github.com/univrsal/tuna/actions/runs/208503829) and it seems like this is fixed.
