### ISSUE TITLE
music control dock state & progress bar

### ISSUE THREAD

**Issue by joschariedl** [univrsal/tuna#25]
Hey univrsal,

the music control dock still doesn't remember it's state of visibility and the progress bar is bound to the refresh rate of the API call, and so doesnt update every second until its at 100%. Is there any way to fix that?

Thx for the plugin and cheers from germany! ;-)

**Comment by univrsal** [comment]
The song progress is updated with every api query since this is the only reliable way to get a correct value if/when the user jumps around in the song or skips it entierly.
I tested the Dock out multiple times and had no issues. Can you give me a obs studio log and exact steps you take?

**Comment by joschariedl** [comment]
Ahh, okay. That explains it. Thank you!

For sure. Will send you an EMail with the log! ;-)

The Music Control isn't docked but always shows up, when starting OBS. So, I switch it off via View->Docks->Music Control, but it always shows up again, restarting OBS.

**Comment by univrsal** [comment]
You can just upload the log in obs and post the link here
![img](https://user-images.githubusercontent.com/8353672/79078849-c5c65880-7cfa-11ea-8ead-7c672660e216.png)

**Comment by joschariedl** [comment]
Here you go: https://obsproject.com/logs/3U-U3us32pc7yxYP

**Comment by iMaJiNair** [comment]
Can you incorporate a tutorial on how to use tuna? 
I have it installed but am having a hard time figuring how to use the program to update song names on the display, let alone figuring how to automatically have the names pull up with each play.. I'm using VLC Player as the source of the playlist. I'm only knowing how to update the songs manually but am in need of automating this task. Please help.

**Comment by iMaJiNair** [comment]
""Where is the song information?
The information is provided via text and image files, which can be configured in the tuna dialog, under Tools > Tuna settings. To display the information you have to add a text and image source and **point them to the text and image file** respectively.""

How to point???

**Comment by iMaJiNair** [comment]
What player is the best? I know you're a great programmer. I just need some clarification LOL.

**Comment by univrsal** [comment]
> Can you incorporate a tutorial on how to use tuna?

Please watch the tutorials on the obs forums page.

> What player is the best? I know you're a great programmer. I just need some clarification LOL.

[MPD](https://www.musicpd.org/) or the VLC source are currently the best option

**Comment by univrsal** [comment]
I gave the latest [build](https://github.com/univrsal/tuna/actions/runs/208503829) a thorough test and the state is definitely saved now. If you don't wan the dock disable it via View > Docks > Music control.
