### ISSUE TITLE
Last.fm support

### ISSUE THREAD

**Issue by djmattyg007** [univrsal/tuna#27]
It would be cool if this plugin could pull the "currently listening to" data from Last.fm. This way it doesn't matter what software I'm using to play music, as long as it has Last.fm support.

**Comment by univrsal** [comment]
![image](https://user-images.githubusercontent.com/8353672/90322808-64ccbc80-df48-11ea-9dd3-4ae609d40596.png)
I got it working, but last.fm doesn't support all options so things like the song progress or release year don't work. It will be part of the next release.
