### ISSUE TITLE
Album art not appearing consistently with VLC source

### ISSUE THREAD

**Issue by floogs** [univrsal/tuna#28]
I'm having album artwork both appearing and not appearing while using a VLC source, using the same audio files in both cases. Obviously the embedded art is valid since it's showing up some of the time, but I just can't figure out what's making it appear sometimes but not others. I've got three separate text files all working reliably so the plugin is generally working fine.

This is with VLC 3.0.10 and OBS 25.0.8. I tailed the log for a bit while toggling the music and overlay on and off to look for clues, but this is all I could find that looked relevant.

```
19:38:39.388: [tuna] Couldn't move existing cover to temp file
19:38:39.388: [tuna] Couldn't move placeholder cover
```

**Comment by floogs** [comment]
Apologies, didn't see that #21 is about roughly the same problem. 

But to add some more detail based on the questions in that issue, I'm working with mp3 and flac and having the same issue with both. Here's the relevant info from an ffmpeg probe on one of the flacs that is showing artwork less than half the time i try it.

```
  Duration: 00:00:23.82, start: 0.000000, bitrate: 508 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
    Stream #0:1: Video: png, pal8(pc), 384x224, 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)
```

**Comment by univrsal** [comment]
I just checked and the error messages in the log shouldn't have anything to do with this.
Tuna just grabs the cover from the vlc cache so it might have something to do with that.
I'll post in #21 if I find a fix for it
