### ISSUE TITLE
Most Recent Update MacOS Version Missing?

### ISSUE THREAD

**Issue by wflieller** [univrsal/tuna#29]
Will you be releasing the most recent release for MacOS?

**Comment by AMDITAR** [comment]
Bump, I'm looking for this as well.  I use tuna on two macs for streaming.

**Comment by univrsal** [comment]
I don't use macOS so it's not exactly high on my priorities, but I'll see if I can fix the existing issues and then update the release

**Comment by univrsal** [comment]
The mac version is currently broken and I don't have much time, it'll be out when it's out

**Comment by skaag** [comment]
Can you at provide some build instructions?

**Comment by univrsal** [comment]
> Can you provide some build instructions?

https://github.com/obsproject/obs-studio/wiki/install-instructions#macos-build-directions
then clone this repository into 
https://github.com/obsproject/obs-studio/tree/master/plugins
and add ``add_subdirectory(tuna)`` to 
https://github.com/obsproject/obs-studio/blob/master/plugins/CMakeLists.txt

**Comment by skaag** [comment]
Thank you, I was able to build OBS and Tuna. I'm going to start testing it now. I can already see the Tuna Progress bar in the list of Outputs, going to test the rest of the functionality now.

**Comment by univrsal** [comment]
The issue is mainly with the dialog in the tools option, see #30 for more information. I'd appreciate any help I can get with it

**Comment by skaag** [comment]
I looked at #30 but I am not 100% sure I am able to reproduce it.

When I open `Tools -> Settings`, my settings in the tabs `Basics` and `Window Title` are saved just fine. It also works if I quit OBS and restart it, it's all still there for me.

What hasn't worked for me is Spotify. For some reason it doesn't like the Authentication code that Spotify gave me. It's this super long code, I paste it in and when I click `Request Token` in the UI, the log shows this error:

```
error: [tuna] Cannot request token without valid credentials and/or auth code!
```

And it doesn't save the token, probably because it fails, so when I re-open that tab the `Authentication code` field is empty.

**Comment by univrsal** [comment]
You need the private api key for tuna, which only I have, you could register your own spotify app and use that, but then you'll also have to get a login page which uses the public token.
Tuna uses these pages:
https://github.com/univrsal/univrsal.github.io/tree/master/auth
and specifically
https://github.com/univrsal/univrsal.github.io/blob/master/auth/login.html#L45
has to use whatever the public id of the spotify app is. I might add an option for people to use their own Api keys, which would allow users to by pass the rate limit which tuna experiences.

**Comment by skaag** [comment]
When I clicked the Login Page it took me to that legal page, I continued and it registered an app with Spotify, which I can see if I go to my Spotify Apps:

![image](https://user-images.githubusercontent.com/169619/83334769-a8732c80-a25d-11ea-9e75-b91e8bf1b3bc.png)

It's just that the token I receive is super long, I have a feeling that's not the right now.

But as you say, maybe that token is what you need to use in your proxy, and accessing spotify directly from within Tuna is the way to go so users can do it on their own without going through your proxy. I am a Spotify Premium user so I'd have full functionality in theory.

Another setting I wasn't able to save is MPD. I don't actually have MPD running, but whatever values I set in there were not saved. Does it want the connection to succeed before it will agree to save the MPD settings?

**Comment by univrsal** [comment]
The token should be fairly long, about 300 characters. The login process is always done through a login mask. Anyone who wanted to use their own API keys would have to set up a login page like the one that tuna uses. I might tweak mine to accept custom api keys, so all authentication could go through it, but I'm not sure if/when that'll happen.

Me not being a premium user doesn't restrict the functions that tuna can access. It only means that if someone who uses tuna doesn't have premium, they will not be able to use certain features, like skipping a song through the plugin.

MPD should save it's settings regardless of whether it's connected so I guess somethings wrong there.

**Comment by univrsal** [comment]
So I have spend some time on the macOS build and got a working version. I had to disable the dock since it seems to be broken.
You can get the build [here](https://github.com/univrsal/tuna/releases/tag/v1.4.2).
