### ISSUE TITLE
Crashes when trying to start, also the UI is not functioning as intended.

### ISSUE THREAD

**Issue by OriginalSchmuck** [univrsal/tuna#3]
![badUI](https://user-images.githubusercontent.com/45401658/68610158-61b21680-0474-11ea-9aca-11cc444e68ec.png)

Here is the crash report (i hope): https://pastebin.com/raw/ruSjphtF

**Comment by univrsal** [comment]
Can you try and use this build and give me the crash report again?
[tuna.debug.zip](https://github.com/univrsal/tuna/files/3832770/tuna.debug.zip)

**Comment by OriginalSchmuck** [comment]
Yes, here you go: https://pastebin.com/raw/gjpcJaAq

**Comment by univrsal** [comment]
thanks, looks like something crashes when it tries to move files around. I'll take a look at it

**Comment by OriginalSchmuck** [comment]
Any idea on the UI?  I'm pretty sure it's not supposed to look like that?

**Comment by univrsal** [comment]
did you install all files correctly? It seems like you're missing the translation files

**Comment by OriginalSchmuck** [comment]
I pulled the plugin folder out of the zip, moved it to C:\Program Files\obs-studio\obs-plugins\64bit
And pulled the .dll from the 64bit folder into the...other 64 bit folder.  So the plugin started working but then looked like that?  I hope I'm explaining this right.

**Comment by univrsal** [comment]
The folder structure is set up in way, that all you have to do is drag the two folders 'obs-plugins' and 'data' into your obs installation directory. Did you do that? You need the data folder because it containts the language file

**Comment by OriginalSchmuck** [comment]
You are the most patient programmer I've ever met.  That worked, and it doesn't crash. Still have no idea how to set it up, like inputs and outputs.  Got a setup guide?

Also thank you.

**Comment by univrsal** [comment]
The outputs are made up of a path and a format. Which basically means that it'll take the song information and format in whatever way you set it up and then saves it to the provided path.
Tuna gets its information either through the Spotify API or from a specific window title.
The obs forum post includes some infos on how to setup spotify or the window title source.

**Comment by OriginalSchmuck** [comment]
Well I'm glad it works, I'll have to figure this out later.  This is why my dad is the programmer and I'm the hardware nerd, because, that was all greek to me.  It's a wonder I can even manage to start a program without setting my computer on fire.

Thanks.

**Comment by OriginalSchmuck** [comment]
I got it. 
God I'm slow.

Thank you for all you do.

**Comment by univrsal** [comment]
Glad to be of service
