### ISSUE TITLE
[Linux] 1.4.2 installation on Manjaro

### ISSUE THREAD

**Issue by jay061996** [univrsal/tuna#31]
Had some issues getting tuna installed but I figured it out.

On my Manjaro system, running `install-linux.sh` moves only the `tuna` folder to be placed at `~/.config/obs-studio/plugins/tuna/tuna` which makes the plugin not even load.

After manually moving `tuna` to be placed at `~/.config/obs-studio/plugins/tuna` the plugin loads, but fails to load `en-US` causing labels to not be correct.

I manged to get `en-US` to load by manually placing it at `~/.config/obs-studio/plugins/tuna/data/locale/en-US.ini`

Now that I've gotten it installed, everything seems normal except `%b` linebreak is not working.

**Comment by univrsal** [comment]
I think I already fixed that in the script, I just haven't gotten around to updating the release

**Comment by MCOfficer** [comment]
In case you're interested, i created an [AUR package](https://aur.archlinux.org/packages/obs-plugin-tuna-bin) for tuna. You can use the AUR from manjaro, too.

**Comment by BLCRAFT-Gaming** [comment]
%b as linebreak also does not work for me.

**Comment by univrsal** [comment]
The line break stuff should be fixed. There's now also a debian installer, and a binary release with a README for all other distros.
