### ISSUE TITLE
Line break format symbol not working

### ISSUE THREAD

**Issue by Khaztaroth** [univrsal/tuna#32]
I recently had to do a fresh install of OBS studio and my plugins. For some reason, the text file for the current song gets written as ARTIST b TITLE instead of actually creating a line break. Interestingly, this wasn't the case when I updated to the latest version of OBS the first time, it only appeared once I did a clean install. The only other plugins I have are InputOverlay, websoquet, and virtual cam.  

![image](https://user-images.githubusercontent.com/10103152/81935245-545e1c00-95be-11ea-9585-896eb8c6f064.png)

**Comment by univrsal** [comment]
try using %e, I added a new specifier for the song label which uses %b. I'll try and update the dialog text

**Comment by Khaztaroth** [comment]
That works perfectly, thanks for the quick answer.
