### ISSUE TITLE
GUI Issue and Functionality not working for VLC: Ubuntu 18, OBS 25.08 Tuna1.4.2

### ISSUE THREAD

**Issue by autominded** [univrsal/tuna#33]
I tried running with Ubuntu 18, OBS 25.08 Tuna1.4.2
It seems not to work i used the same video on YouTube for tutorial, please check. It works flawlessly on Windows no doubt.
Please check for Ubuntu 18 Thanks.
So it shows on tuna dock the name of the song playing but not in the file.
The GUI naming is screwed, and the functionality isnt working for VLC now playing
![tuna option](https://user-images.githubusercontent.com/19249530/83388296-d5654200-a40b-11ea-8bfd-a12ed58160e0.JPG)
![tunszgui](https://user-images.githubusercontent.com/19249530/83388315-dc8c5000-a40b-11ea-8dd9-a4466132c550.JPG)

**Comment by univrsal** [comment]
There's now  a debian installer, please try that once I make a new release.
