### ISSUE TITLE
MPD support on Windows

### ISSUE THREAD

**Issue by NovaPhoenix** [univrsal/tuna#34]
Is there a reason it isn't enabled on Windows? I've got MPD running and I'd like to be able to connect to it.

**Comment by univrsal** [comment]
There doesn't seem to be a ready build of libmpdclient on windows and I didn't bother to compile it myself

**Comment by univrsal** [comment]
I couldn't get libmpdclient to compile on windows so this will most likely not happen

**Comment by NovaPhoenix** [comment]
Keep in mind, I'm not a developer, but I just compiled it through msys2 and it spat out a dll. Maybe it'll help?
https://transfer.sh/11dtI8/libmpdclient.dll.a if you're unable to get that to work

**Comment by univrsal** [comment]
MPD support should technically be enabled with the next push, you can get the build from the github [actions](https://github.com/univrsal/tuna/actions) (once I'm done) just look for the latest run at the top and then download the build in the artifact section. There's an installer and a normal binary build.

**Comment by NovaPhoenix** [comment]
I've tested the latest nightly build but the MPD tab doesn't show up in the tuna settings menu. Not sure if this is the push you were talking about or not, so just wanted to let you know

**Comment by univrsal** [comment]
Oh crap, I forgot to remove the part the hides the mpd tab on windows. Next nightly build should show it.

**Comment by univrsal** [comment]
Just tested the new nightly and it works now.
