### ISSUE TITLE
Slow to update files when changing tracks on Spotify and folder is unfocused

### ISSUE THREAD

**Issue by fbnlsr** [univrsal/tuna#36]
I've noticed a strange behaviour that I can't seem to explain. When changing tracks on Spotify (polling set to 1000ms), it can take up to 30 seconds to show on OBS. However, if the folder where I write the tuna files on is opened in my file browser the changes are almost instant.

I can't figure out if it's a problem from Tuna, OBS, or my OS.

OBS 25.0.3
Pop_OS! 20.04

**Comment by univrsal** [comment]
It's a problem with the Spotify API, they limit the rate of requests that Tuna can send, and since it queries it every second for every single user currently using the plugin it gets limited quite a lot.

**Comment by fbnlsr** [comment]
What I'm having a hard time wrapping my head around is why changes get instantly done when the file browser is opened. The call to Spotify's API is the same, but it's like suddenly it replies instantly. It's something that I can reproduce, so I was wondering if the problem lies more on the "writing files to the disk" part.

**Comment by univrsal** [comment]
What file browser? Also can you upload the obs log?

**Comment by fbnlsr** [comment]
Pop_OS!'s default file browser.

Log file is here: https://obsproject.com/logs/sd0Q9jQtLQLwgBQ3

The `Couldn't move placeholder cover` error is normal: I've removed it so it displays nothing when no music is playing.

This morning it seems to be working a bit better.

**Comment by univrsal** [comment]
Seems more like a coincidence, the file browser has no impact on the plugin. I've fixed the error spamming, but haven't made a new release yet.

**Comment by fbnlsr** [comment]
Alright, I'll monitor this I guess. I'll probably lower the interval to Spotify's API and see what it does as well. Or are you handling the `Retry-After` header that's sent back as well? In that case I'll just try and see if I can reproduce the bug again.

**Comment by univrsal** [comment]
Yeah they're handled, it should print it into the log, but it might be debug only. I was also considering allowing users to register their own spotify app and use the API keys of that so they get a separate threshold

**Comment by fbnlsr** [comment]
You mean every tuna user is on the same API key? Woah, I'm surprised it didn't get banned. This would help things tremendously indeed.

**Comment by univrsal** [comment]
Well this is how the API is intended to be used. There's no reason to ban it since they have the threshold for exactly that reason. Also registering your own Spotify app isn't exactly something the average user would put up with anyways.

**Comment by katokatokatokatokatokato** [comment]
1 api key for each user is definitely the way to go as I've noticed that it definitely gets worse overtime, also performance varies tremendously depending of the time you are using it

**Comment by fbnlsr** [comment]
> 
> 
> Well this is how the API is intended to be used. There's no reason to ban it since they have the threshold for exactly that reason. Also registering your own Spotify app isn't exactly something the average user would put up with anyways.

Perhaps it could be an option? With the proper tutorial it's still something that could be done and could help tremendously.

**Comment by univrsal** [comment]
If I add it it would definitely be an option

**Comment by univrsal** [comment]
I've pushed changes that allow this option, which should remove any API timeouts. Check out the artifacts generated by the latest run [here](https://github.com/univrsal/tuna/actions/runs/206271637) and give it a try. I have made a video explaining what needs to be done to use a custom Spotify ID, but I'll upload it tomorrow.
