### ISSUE TITLE
OBS 25.0.8 / VLC sources

### ISSUE THREAD

**Issue by Finch-Tamo** [univrsal/tuna#37]
Hi !
I got this error and i can't use VLC sources with Tuna :( 
In logs, it's say is invalid with the last libobs.

> 20:31:07.805: [tuna] Loading v2020.04.12 16:18
20:31:07.805: [tuna] libobs version 25.0.8 is invalid. Tuna expects 25.0.4 for VLC sources to work
20:31:07.805: [tuna] User force enabled VLC support
20:31:07.866: [tuna] Loaded libVLC. VLC source support enabled
20:31:07.936: [tuna] Registered Spotify (id: spotify)
20:31:07.936: [tuna] Registered MPD (id: mpd)
20:31:07.936: [tuna] Registered VLC (id: vlc)
20:31:07.936: [tuna] Registered Window Title (id: window)
20:31:07.940: [tuna] Loaded 1 outputs
20:31:07.941: [tuna] Couldn't move existing cover to temp file
20:31:07.941: [tuna] Couldn't move placeholder cover

**Comment by univrsal** [comment]
Can you give me the entire log? The error shouldn't prevent it from working

**Comment by Finch-Tamo** [comment]
> 22:34:40.586: CoInitializeEx succeeded: 0x00000001
22:34:40.587: CPU Name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
22:34:40.587: CPU Speed: 2808MHz
22:34:40.587: Physical Cores: 4, Logical Cores: 8
22:34:40.587: Physical Memory: 16340MB Total, 10156MB Free
22:34:40.587: Windows Version: 10.0 Build 19041 (release: 2004; revision: 329; 64-bit)
22:34:40.587: Running as administrator: true
22:34:40.587: Aero is Enabled (Aero is always on for windows 8 and above)
22:34:40.587: Windows 10 Gaming Features:
22:34:40.587: 	Game Bar: Off
22:34:40.587: 	Game DVR: Off
22:34:40.587: 	Game DVR Background Recording: Off
22:34:40.587: 	Game Mode: Off
22:34:40.590: Sec. Software Status:
22:34:40.591: 	Antivirus Microsoft Defender: enabled (AV)
22:34:40.591: 	Pare-feu Windows: enabled (FW)
22:34:40.592: Current Date/Time: 2020-06-25, 22:34:40
22:34:40.592: Browser Hardware Acceleration: true
22:34:40.592: Portable mode: false
22:34:41.133: OBS 25.0.8 (64-bit, windows)
22:34:41.133: ---------------------------------
22:34:41.151: ---------------------------------
22:34:41.151: audio settings reset:
22:34:41.151: 	samples per sec: 48000
22:34:41.151: 	speakers:        2
22:34:41.152: ---------------------------------
22:34:41.152: Initializing D3D11...
22:34:41.152: Available Video Adapters: 
22:34:41.153: 	Adapter 0: NVIDIA GeForce GTX 1070
22:34:41.153: 	  Dedicated VRAM: 4178575360
22:34:41.153: 	  Shared VRAM:    4272228352
22:34:41.153: 	  PCI ID:         10de:1be1
22:34:41.154: 	  Driver Version: 27.21.14.5148
22:34:41.154: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=75, name=
22:34:41.154: 	  output 1: pos={1920, 0}, size={1680, 1050}, attached=true, refresh=59, name=X222W
22:34:41.155: Loading up D3D11 on adapter NVIDIA GeForce GTX 1070 (0)
22:34:41.244: D3D11 loaded successfully, feature level used: b000
22:34:41.244: DXGI increase maximum frame latency success
22:34:41.244: D3D11 GPU priority setup success
22:34:41.813: ---------------------------------
22:34:41.813: video settings reset:
22:34:41.813: 	base resolution:   1920x1080
22:34:41.813: 	output resolution: 1280x720
22:34:41.813: 	downscale filter:  Bicubic
22:34:41.813: 	fps:               60/1
22:34:41.813: 	format:            NV12
22:34:41.813: 	YUV mode:          601/Partial
22:34:41.813: NV12 texture support enabled
22:34:41.815: Audio monitoring device:
22:34:41.815: 	name: Par défaut
22:34:41.815: 	id: default
22:34:41.815: ---------------------------------
22:34:41.828: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
22:34:41.830: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
22:34:41.883: [AMF] Unable to load 'amfrt64.dll', error code 126.
22:34:41.885: [AMF] AMF Test failed due to one or more errors.
22:34:41.885: Failed to initialize module 'enc-amf.dll'
22:34:41.935: [obs-browser]: Version 2.8.6
22:34:41.954: NVENC supported
22:34:42.154: Failed to load 'fr-FR' text for module: 'tuna.dll'
22:34:42.154: [tuna] Loading v2020.04.12 16:18
22:34:42.154: [tuna] libobs version 25.0.8 is invalid. Tuna expects 25.0.4 for VLC sources to work
22:34:42.154: [tuna] User force enabled VLC support
22:34:42.188: [tuna] Loaded libVLC. VLC source support enabled
22:34:42.251: [tuna] Registered Spotify (id: spotify)
22:34:42.251: [tuna] Registered MPD (id: mpd)
22:34:42.251: [tuna] Registered VLC (id: vlc)
22:34:42.251: [tuna] Registered Window Title (id: window)
22:34:42.251: [tuna] Loaded 1 outputs
22:34:42.254: [tuna] Couldn't move existing cover to temp file
22:34:42.254: [tuna] Couldn't move placeholder cover
22:34:42.264: VLC found, VLC video source enabled
22:34:42.293: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
22:34:42.293: No blackmagic support
22:34:42.322: ---------------------------------
22:34:42.322:   Loaded Modules:
22:34:42.322:     win-wasapi.dll
22:34:42.322:     win-mf.dll
22:34:42.322:     win-dshow.dll
22:34:42.322:     win-decklink.dll
22:34:42.322:     win-capture.dll
22:34:42.323:     vlc-video.dll
22:34:42.323:     tuna.dll
22:34:42.323:     text-freetype2.dll
22:34:42.323:     rtmp-services.dll
22:34:42.323:     obs-x264.dll
22:34:42.323:     obs-vst.dll
22:34:42.323:     obs-transitions.dll
22:34:42.323:     obs-text.dll
22:34:42.323:     obs-qsv11.dll
22:34:42.323:     obs-outputs.dll
22:34:42.323:     obs-filters.dll
22:34:42.323:     obs-ffmpeg.dll
22:34:42.323:     obs-browser.dll
22:34:42.323:     image-source.dll
22:34:42.323:     frontend-tools.dll
22:34:42.323:     enc-amf.dll
22:34:42.323:     decklink-ouput-ui.dll
22:34:42.323:     coreaudio-encoder.dll
22:34:42.323: ---------------------------------
22:34:42.323: ==== Startup complete ===============================================
22:34:42.342: All scene data cleared
22:34:42.342: ------------------------------------------------
22:34:42.427: WASAPI: Device 'VoiceMeeter Aux Output (VB-Audio VoiceMeeter AUX VAIO)' [48000 Hz] initialized
22:34:42.427: [Loaded global audio device]: 'VM - Aux'
22:34:42.471: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: VM - Aux)
22:34:42.471: 
22:34:43.195: [window-capture: 'Capture de fenêtre'] update settings:
22:34:43.195: 	executable: firefox.exe
22:34:43.459: Switched to scene 'Before-start'
22:34:43.459: ------------------------------------------------
22:34:43.459: Loaded scenes

**Comment by Finch-Tamo** [comment]
After un fresh install of OBS + VLC, it works ! I don't know why but it work ... :) Thx for your time ;)
