### ISSUE TITLE
Tags with japanese unicode characters not displaying cover art properly

### ISSUE THREAD

**Issue by RaccoonViolet** [univrsal/tuna#38]
Hi there, I have Tuna set up with cover art which has been working great, but for some tracks I have with Japanese characters (or other odd unicode characters) in the tags the cover art does not work. I've attached an example image

![04_56_01](https://user-images.githubusercontent.com/9168199/86201858-8ae4fb80-bb58-11ea-89cd-77563617a998.png)

**Comment by univrsal** [comment]
Man I thought I fixed that. What audio source are you using?

**Comment by RaccoonViolet** [comment]
i'm using the VLC source

**Comment by univrsal** [comment]
In that case it has probably less to do with the Unicode and more with the audio file or how VLC caches album covers. Does it always happen with a specific file or every single file that uses Unicode? Have you tried removing the characters with something like mp3tag to see if that fixes it (just to pinpoint the issue).

**Comment by RaccoonViolet** [comment]
Removing the characters from the tags does fix it, yes. it's happened with even common characters like é as well

**Comment by univrsal** [comment]
Well I just gave it a spin and it seems that the cover url uses the percent encoding (e.g. ``é`` turns into ``%C3%A9``) which I'll have to decode otherwise it can't find the files since they don't use the percent encoding. I'll see what I can do

**Comment by univrsal** [comment]
This should be fixed with the next push, you can get a test build from the github [actions](https://github.com/univrsal/tuna/actions) (once I'm done) just look for the latest run at the top and then download the build in the artifact section. There's an installer and a normal binary build.
