### ISSUE TITLE
Some tracks in my library are causing OBS to crash with tuna enabled

### ISSUE THREAD

**Issue by RaccoonViolet** [univrsal/tuna#39]
This one is difficult for me to pinpoint to report since I cannot identify which tracks in-particular are causing OBS to crash (since the tag display doesn't update when OBS crashes). Even though the "OBS has crashed!" dialogue window pops up, OBS itself is still running in the background with the music playing until I click Yes or No and close the crash popup.

A little bit more info which may help: I was getting these crashes on a set of MP3s I'd imported to the VLC player earlier, but I managed to fix those crashes by removing some additional musicbrainz metadata that was embedded in the MP3 files. However, it seems these new crashes are happening on MP3s that don't have this additional metadata as well.

I have attached the last crash dump if it's of any help.
[Crash 2020-07-09 05-22-35.txt](https://github.com/univrsal/tuna/files/4894528/Crash.2020-07-09.05-22-35.txt)

![image](https://user-images.githubusercontent.com/9168199/86996849-a2e5fc00-c1a4-11ea-8264-ed340c72c726.png)

Update: I have identified one of the MP3 files causing issues, no idea why.
https://f.violet.pm/2020/07/09/33.%20Straight%20to%20Hell1.mp3

**Comment by univrsal** [comment]
I'll try and look into it

**Comment by RaccoonViolet** [comment]
I think I've figured out what's causing the crashes. Some of the MP3 files I own have additional tags embedded in them that my usual player (foobar2000) cannot see. After loading each of the MP3 files into mp3tag and removing the additional tags the crashes seem to be resolved. The most common additional tags that were causing issues were musicbrainz tags

**Comment by univrsal** [comment]
I don't have much time on my hand currently, so I can't look into it, but the issue is that the metadata is queried by VLC and not the plugin, so I don't even know if I can fix this.

**Comment by univrsal** [comment]
I just gave it a quick test and couldn't reproduce the issue, can you tell me exactly what tags and what values caused issues?

**Comment by RaccoonViolet** [comment]
I believe it's the musicbraiz tags, if you can't re-produce the issue it may be something on my end. I've temporarily fixed this myself by just removing the musicbrainz tags from all the music in my library. Here's a pic from mp3tag

![image](https://user-images.githubusercontent.com/9168199/90089532-8ac04a00-dd19-11ea-88a1-9e1b6987dc25.png)

**Comment by univrsal** [comment]
I just added that exact tag with the same value to a file and now it's crashing, I'll see if I can find the cause.
