### ISSUE TITLE
Trouble installing/using

### ISSUE THREAD

**Issue by Forleafe** [univrsal/tuna#4]
In linux: I've followed the instructions, created the folder, copied the contents into it, and have launched OBS.

I don't see anything different, and I can't find where I'd access this plugin's settings. I don't know if this is working properly or not.

Any help or general guidance would be deeply appreciated. There just isn't much written here.

**Comment by univrsal** [comment]
Can you give me a log? There's currently some issues with the plugin on linux, because I only tested it on Arch Linux

**Comment by Forleafe** [comment]
[2019-12-22 18-17-51.txt](https://github.com/univrsal/tuna/files/3993110/2019-12-22.18-17-51.txt)

Here's the log! Thanks so much <3

**Comment by Forleafe** [comment]
@univrsal So I've run this and it's now working:
sudo apt install libmpdclient2

However, Can I just a get a super quick n' dirty of how this thing works with window title capture? I'm just not really understanding how this thing works.

I went to the tab that was "Window capture mode" I set the searchterm as "YouTube" but now what else do I need to do? Where is the title going to get outputted?

**Comment by univrsal** [comment]
It outputs the song as defined in the basics tab. You can have multiple outputs, which consists of a path and a format. The plugin will write the format to the path it's paired with.
By default it outputs into the home directory.
This might not work though because I've had someone else who had issues with that on Ubuntu.

**Comment by Forleafe** [comment]
@univrsal Yeah, every time I try adding any file path, no matter the location I choose, it will always not let me choose and will say 

Output Error
The provided data is incorrect. Make sure the format isn't empty and the path is valid

Not sure if I'm doing something wrong. I keep naming the file song.txt

**Comment by Forleafe** [comment]
@univrsal 
[2019-12-22 22-38-00.txt](https://github.com/univrsal/tuna/files/3993555/2019-12-22.22-38-00.txt)

I manually created the song.txt file, selected it, and then every time I would hit okay, I'd get a consistent crash and it would kill OBS. I've attached the log. But the trouble line is:

10:38:01 PM.077: [tuna] Error loading output json at line 2 (col: 4): ']' expected near end of file

I'm on ubuntu 18.04

**Comment by univrsal** [comment]
I looked into it and fixed an issue with saving and I'll make a new build shortly

**Comment by univrsal** [comment]
So it seems like there was an issue when saving the outputs to JSON, I'm using a different way of creating JSON files, which should fix the issue. Can you try the attached build and install it the same way?
[tuna.v1.3.2.ubuntu.x64.zip](https://github.com/univrsal/tuna/files/4000758/tuna.v1.3.2.ubuntu.x64.zip)

**Comment by univrsal** [comment]
I'll just close this for now. If you still have issues just comment again
