### ISSUE TITLE
Basic Settings Not Saving OBS - Mac OS Catalina 10.15.6

### ISSUE THREAD

**Issue by russianspaceman** [univrsal/tuna#41]
Spotify connection works perfectly, but when navigating back to the basics tab and attempting to edit/add/remove a new song format and song info path, the settings do not save after hitting APPLY and OK. Please help me out.

**Comment by russianspaceman** [comment]
I was referring to the song info outputs not saving. If there is any other method to alter settings under the plugin folder manually to "force" the change to the song info output settings, please let me know.

**Comment by univrsal** [comment]
I need the obs studio log

**Comment by AMDITAR** [comment]
I worked through a solution to this [in issue 30.](https://github.com/univrsal/tuna/issues/30)  Dev should add granting full disk access to OBS to the installation instructions under Catalina.

**Comment by univrsal** [comment]
I'll close this for now and post updates in #30
