### ISSUE TITLE
Unicode characters not displaying correctly

### ISSUE THREAD

**Issue by jamedwarnton** [univrsal/tuna#42]
I'm having a weird issue where unicode characters (tested Japanese and Korean so far) won't display correctly on the text source. Interestingly, they are working in the Music Control dock from Tuna, and displaying fine in VLC and the mp3 tags. 

If I switch the font on the OBS text source and change the 'writing system' to the appropriate language, the unicode characters display but then the latin characters are placed by empty boxes!

Any help would be appreciated!

**Comment by univrsal** [comment]
Are you sure the font that you're using supports all characters? Arial is your best bet.

**Comment by jamedwarnton** [comment]
![Screenshot from 2020-07-26 21-15-01](https://user-images.githubusercontent.com/33632793/88488597-25810080-cf86-11ea-870f-64b9a92aac27.png)
This was what I was getting. However a couple of minutes ago I toggled between Japanese and Korean and it switched to a Noto font which seems to be displaying unicode and latin correctly, so somehow fixed itself? I haven't switched to another font to check if it's just this one though.

**Comment by univrsal** [comment]
Yeah fonts are a bit of an issue on Linux. On Windows Arial supports almost all characters, but the Arial on linux doesn't. Most Noto fonts are also only specialized on a certain language, which means it'll only support Korean and most latin characters, or Japanese and Latin, so there's no goto font that'll support all. The only one I've ever found is Unifont, but that's a bitmap font so it doesn't look all that appealing and also doesn't seem to work in obs. The Noto CJK should work well enough as long as you don't need anything else like Arabic etc.
There's a [plugin](https://obsproject.com/forum/resources/text-pango-multi-language-and-emoji.656/) which fixes this, if you still run into issues.

**Comment by jamedwarnton** [comment]
Appreciate the quick response and the work you've put in, everything else working well :)
