### ISSUE TITLE
%e and %b mislabeled in Output editor

### ISSUE THREAD

**Issue by ssbmoro** [univrsal/tuna#43]
Hello,

I was setting up tuna for the first time and noticed an apparent mislabeling of the special prompts to display the publisher and a line break. I added a %e to show the Song label (edited to say "Publisher" in the track I'm testing, since it was blank previously). It appeared as a line break. I added a line break to test further, and it appears that %e and %b are switched in either the instructions in the output editor or the code is applying the wrong label to the characters.

Test input: "Now playing - %e - %b - %a - %t"
![image](https://user-images.githubusercontent.com/69113632/89538762-f7db5900-d7c8-11ea-8a5a-6605120e201e.png)

Expected output: 

> "Now playing - Publisher
>  \- Zelda & Chill - Fairy Fountain"

Actual output:
![image](https://user-images.githubusercontent.com/69113632/89538856-12adcd80-d7c9-11ea-8b44-1b8238225ea7.png)

> "Now playing - 
>  \- Publisher - Zelda & Chill - Fairy Fountain"

**Comment by univrsal** [comment]
Fixed in 6037844b2b11f080b39c3bec70930a9d952df30d
