### ISSUE TITLE
Progress bar, sometimes freezes in the latest version 1.4.2

### ISSUE THREAD

**Issue by Glazami** [univrsal/tuna#45]
Progress bar, sometimes freezes, and in general it jerks and does not move smoothly
It can be fixed?

**Comment by univrsal** [comment]
It is more or less already fixed, but if you use spotify it will always be a bit janky because the spotify API limits the amount of requests that can be made.

**Comment by Glazami** [comment]
Oh, I thought it was the polling method.
In another application, the progress bar did not freeze, but the application itself was not convenient.
Thanks for the answer.
