### ISSUE TITLE
[REQ] Write play time remaining to file?

### ISSUE THREAD

**Issue by geslotencirkel** [univrsal/tuna#46]
Hi is it possible to add a way to write the remaining playtime to a text file? 

I am lost since Duration isn't shown with my files, but progress bar size and Media Controls v 0.2.2 do show time remaining correctly - would be great to write those to a file just like Progress (%p) does right now

**Comment by univrsal** [comment]
what source are you using?

**Comment by geslotencirkel** [comment]
VLC Source ..

**Comment by univrsal** [comment]
Duration is working for me, I think I've fixed that since the last release. Time left is definitely possible, I'll look into it.

**Comment by geslotencirkel** [comment]
awesome - would be a great trigger

**Comment by univrsal** [comment]
Added in c2ea3439f5c8488771fa0e7ac85c1654a466aa99
