### ISSUE TITLE
Release assets unexpectedly changed

### ISSUE THREAD

**Issue by MCOfficer** [univrsal/tuna#51]
Hello,

@ aurifier on AUR just [noticed that the package was failing to build](https://aur.archlinux.org/packages/obs-plugin-tuna-bin/#comment-762797). Since the package worked perfectly fine for 1.4.2 before, this can only be explained by someone updating the release assets for 1.4.2.

In case this is correct, I'd like to raise awareness that such changes can cause quite some problems downstream. It's not critical since the AUR checks the file's hash before using it, but it's just annoying when a package breaks without anything to notify the maintainer. Even small changes should be made by pushing a new release, for example [that one time when i forgot to bump the version number before tagging](https://github.com/EndlessSkyCommunity/ESLauncher2/releases/tag/v0.5.1).

**Comment by univrsal** [comment]
I don't know I probably changed the script or something, nothing that warrants a new release version. You can check the checksum of the .so file if you want to be sure.

**Comment by MCOfficer** [comment]
I guess this is simply a different lens. From a packaging PoV anything, even a change to the package itself, warrants a new version. 

I just wanted to clarify that for me and everyone using tuna via the AUR, non-pinned release assets are a hassle. Whenever an asset changes, the hash changes, and thus the installation fails. There's no way around that.

**Comment by univrsal** [comment]
Well I'm not doing it on purpose. I don't think I'll have to change the script anymore since it should work now. I'll keep this in mind for future releases.

**Comment by MCOfficer** [comment]
All good. Thanks!
