### ISSUE TITLE
Can Yandex Music be added to the list of supported sources?

### ISSUE THREAD

**Issue by Glazami** [univrsal/tuna#54]
Will there be such an opportunity?

**Comment by univrsal** [comment]
I did a quick search and it seems like the yandex API does not allow for the retrieval of the currently playing song. So unless that changes I can't add support for it.

**Comment by Glazami** [comment]
There is a function of the last played track. I can use my account to continue listening to music on another device.

**Comment by univrsal** [comment]
Well if you can find me the documentation I'll take a look at it. Just because the official service allows it doesn't mean it's accessible to thirdparty developers.

**Comment by Glazami** [comment]
[yandex music api documentation](https://yandex-music.readthedocs.io/ru/latest/yandex_music.client.html )
This can help?

**Comment by univrsal** [comment]
No, because it's in Russian and google translate isn't of any help

**Comment by Glazami** [comment]
https://github.com/Winster332/Yandex.Music.Api
https://winster332.github.io/Yandex.Music.Api
https://github.com/itsmepetrov/yandex-music-api
is there no necessary information?

**Comment by univrsal** [comment]
No, none of these mention anything about getting the currently playing song and from what I can tell it's just not possible.

**Comment by Glazami** [comment]
This function is really present, perhaps it is among the hidden or not described functions.
Many people say that api is complex.
They say that every time the application is opened, a new access token is generated.

**Comment by Glazami** [comment]
It might be worth doing easier, yandex music supports Scrobbling on Last.fm

**Comment by Glazami** [comment]
Or is Last.fm no longer supported on Tuna?

**Comment by univrsal** [comment]
I just added support for last.fm, if the function is present feel free to point me to it.

**Comment by Glazami** [comment]
https://yandex.ru/support/music/users/transmission.html?lang=en

**Comment by univrsal** [comment]
As I said last.fm support has already been added.

**Comment by Glazami** [comment]
https://s8.hostingkartinok.com/uploads/images/2020/09/3e589b5a3042efe50eba49ce9ed61262.png

**Comment by univrsal** [comment]
you're not using the latest version, and for now it's probably better because it has some issues

**Comment by Glazami** [comment]
https://s8.hostingkartinok.com/uploads/images/2020/09/bbc3031b84b40ef7eeeb8b22f066db2f.png
I installed the latest version 1.5 and after applying the configuration changes the osb crashes.
in the folder with reports the file in "obs-studio\bin\64bit\qt5widgets.dll" appears to be a problematic but this problem appeared three times in a row and then disappeared.

**Comment by univrsal** [comment]
Yes just like I said, it has some issues.

**Comment by Glazami** [comment]
But now there is last.fm 😀

**Comment by Glazami** [comment]
https://github.com/MarshalX/yandex-music-api
