### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by Jayuupee** [univrsal/tuna#55]
I am finiding the UI really really hard to navigate, it's like some vital piece of coding is missing.
![tuna](https://user-images.githubusercontent.com/70598546/91886576-6ead2a00-ec81-11ea-9318-e6ba187c89fe.png)

Could you please help me :(

**Comment by univrsal** [comment]
You didn't install the language files currectly, did you use the installer?

**Comment by Jayuupee** [comment]
I downloaded from the website, using the ZIP file - then dragged my Plugin files over to the OBS folder

Where can I find the language files
________________________________

**Comment by univrsal** [comment]
In the zip file, or use the installer

**Comment by Jayuupee** [comment]
thank you, you're a star, I managed to fix it but now my OBS closes every time i press okay or apply so I think I'm gonna just uninstall - thanks anyway
________________________________

**Comment by univrsal** [comment]
use the previous release, see #53
