### ISSUE TITLE
MPD not working

### ISSUE THREAD

**Issue by Readek** [univrsal/tuna#57]
I'm running Arch. Whenever I try to use MPD in tuna, it just doesn't work (it always displays no song playing) no matter what I do. The connection is local. In theory, all you have to do is open a mpd music player like Cantata and it will work, right? Using Window Title + youtube or another player like VLC works. Tried on both the latest version and in v1.4.2.

**Comment by univrsal** [comment]
It should work. I have it connected to mpd without any issues. Can you upload the log file?

**Comment by Readek** [comment]
The log gets spammed with:
```19:28:50.416: [tuna] mpd connection to localhost:1608 failed with error Connection refused
19:28:50.416: [tuna] Couldn't move existing cover to temp file
19:28:50.416: [tuna] Couldn't move placeholder cover```

https://paste.ubuntu.com/p/gPqcymshWD/

**Comment by univrsal** [comment]
Well there you have it, is MPD actually running on the default port (6600)? What connection configuration is cantata using?  Also I accidentally closed the issue, woops.

**Comment by Readek** [comment]
Nevermind... I spent all this time searching how to know which port is the mpd process using. But yeah, I thought just by using cantata I would have a local MPD connection. Guess I actually have to set that up.
