### ISSUE TITLE
Not pulling song pictures

### ISSUE THREAD

**Issue by AspiringPokerPro** [univrsal/tuna#58]
Hello,

I have jazz playlist set up and I am using VLC to play in obs.  Tuna is not picking put the song image files.  There is just a big question mark.  Any ideas why?  Thanks for this plug in it works great otherwise.

**Comment by univrsal** [comment]
Do the individual song files actually have a cover embedded?

**Comment by AspiringPokerPro** [comment]
I download my music from epidemicsound dot com.  How can I tell if the image is embedded?

**Comment by univrsal** [comment]
Do any other players show a cover? VLC might download the cover separately, so if you want to be really sure use something like mp3tag and see if it shows a cover when you open the file

**Comment by evolfox** [comment]
Hello. I have the same issue. I am using the VLC plugin in OBS to play a random playlist. Files are in FLAC format. For each album, a cover.jpg file is present in the same folder as the .flac files. The cover is displayed with foobar2000 or if I open the file with VLC but does not display with tuna.

**Comment by DavidScann** [comment]
Facing the same issue, except I can verify that the image is embedded onto the metadata of every single one of my files. There's seemingly no pattern as to which song works and which doesn't...
Like so:
https://a.uguu.se/V5OvIW7oohXL_Dd3QKgPbo1.gif

**Comment by univrsal** [comment]
> > Facing the same issue, except I can verify that the image is embedded onto the metadata of every single one of my files. There's seemingly no pattern as to which song works and which doesn't...
> > Like so:
> > https://a.uguu.se/V5OvIW7oohXL_Dd3QKgPbo1.gif
> 
> VLC works fine with my album covers, but it seems that Tuna can't read the Cover Art of songs with Japanese titles or album titles. I erased the Japanese from the songs with mp3tag and they work now. Funnily, a song with no kanji works fine.
> Maybe certain characters (in this case, kanji) cause this to happen?
> See:
> https://imgur.com/a/ap4cP2W

![image](https://user-images.githubusercontent.com/8353672/131246045-6bc3f300-fec3-4dee-8a9b-a0e5595aad85.png)
Works fine for me, so I assume it's a Windows issue which to this day still does not use UTF8 by default like very single other operating system.
