### ISSUE TITLE
Google Play Music™ Desktop Player Integration not working

### ISSUE THREAD

**Issue by Encarton** [univrsal/tuna#59]
Tuna isn't working right for me.
It constantly crashes whenever I try to make an adjustment to the settings.

Video of the Crash: https://streamable.com/4ocjx7
Video 2 with GPMDP open & visible: https://streamable.com/1fv3q2
No Crash Logs were created by OBS and nothing of note happens in the standard logs either.

Eventually, and very randomly, it finally let me apply the changes without taking out OBS, but now it isn't working with Google Play Music™ Desktop Player at all. It just says "No song playing" and leaves it at that. If I swap to Spotify (while the settings don't crash OBS), that works just fine.

Video of Tuna ignoring GPMDP but working with Spotify: https://streamable.com/d98rnz
(Note: In the clip, audio is coming from Google and Spotify is playing but muted)

I have attempted to reinstall the plugin, as well as wipe out the configs and start fresh to no result.
In fact, when I start fresh, the constant crashing on settings change bug comes back which is why I have no idea what is going on with it. Only after repeatedly trying to be able to do a setting change does it eventually let you apply w/o taking out OBS.

**Comment by univrsal** [comment]
I am aware of the crashes, gpmdp should work but I haven't tested it on windows.

**Comment by univrsal** [comment]
fixed in 2e6405a @kyrthrix

**Comment by kyrthrix** [comment]
Thanks so much! I'm still struggling to get it to work, but it's probably my own lack of understanding at this point. :')

**Comment by univrsal** [comment]
did you install the latest nightly build? Because I haven't made a new release yet
