### ISSUE TITLE
Tuna not loaded: No such file or directory

### ISSUE THREAD

**Issue by treier57lol** [univrsal/tuna#6]
Using Kubuntu 19.04, running OBS Studio 24.0.3 (flatpak). Tuna isn't loaded, libjansson4 and libmpdclient2 are installed. Any other dependencies needed? I see no reason why it shouldn't load with the flatpak version.

`16:23:03.620: os_dlopen(/home/treier57lol/.var/app/com.obsproject.Studio/config/obs-studio/plugins/tuna/bin/64bit/tuna.so->/home/treier57lol/.var/app/com.obsproject.Studio/config/obs-studio/plugins/tuna/bin/64bit/tuna.so): libjansson.so.4: cannot open shared object file: No such file or directory
16:23:03.621: Module '/home/treier57lol/.var/app/com.obsproject.Studio/config/obs-studio/plugins/tuna/bin/64bit/tuna.so' not loaded`

**Comment by univrsal** [comment]
flatpak and snaps versions don't seem to work, because of the sandboxing. Did you install the dependencies on you system? Because the flatpak version does not seem to load those dependencies

**Comment by treier57lol** [comment]
On the apt version it works fine, so it is a flatpak problem. I would use the apt version, but it has some issues like not detecting NVENC for some odd reason, but that has nothing to do with Tuna.

**Comment by univrsal** [comment]
As I said I can't do much about that. You can try copying the libraries but other than that I have no idea what might fix the problem

**Comment by treier57lol** [comment]
So I have no idea how to copy libraries but I will try using the apt version from now on, that fixes the issue.

But now Tuna crashes when I try to load an output file. I will make a new issue about it.
