### ISSUE TITLE
Unable to add song info output

### ISSUE THREAD

**Issue by jeffovertime** [univrsal/tuna#60]
Repro:

1. Open Tuna Settings
2. Select Basics tab
3. With Spotify Song Source selected, click "Add new"
4. Input information in new window
5. Click OK
6. Observe that nothing has been added to the list of Song Info Outputs

Additional note: the explorer button for song info path in the Output Editor is unresponsive

This issue was found using Tuna v1.5.0 in OBS Studio 25.0.8

**Comment by dlecina** [comment]
Same exact issue, at least on Windows 10. Cover path and progress bar are working, however. Only song info outputs are missing.

**Comment by geslotencirkel** [comment]
try the latest nightly build

**Comment by dlecina** [comment]
I used the latest one in Releases. Is there a packaged nightly build I can try for Windows? I do not have the means to compile one myself. Sorry in advance if I am missing something obvious.

**Comment by geslotencirkel** [comment]
also had no idea until this issue - just click in the github menu
![image](https://user-images.githubusercontent.com/12006521/92610164-b0f4ed80-f2b7-11ea-8684-c121dc32a506.png)

and then Nightly and the first one on the list
![image](https://user-images.githubusercontent.com/12006521/92610291-d681f700-f2b7-11ea-8421-facfaa15ef04.png)

then it'll take you to downloads
![image](https://user-images.githubusercontent.com/12006521/92610338-e3064f80-f2b7-11ea-8268-7c3775f6cb48.png)


there's still a known issue with a crash on exit in that one, but everything else seems good here.

**Comment by univrsal** [comment]
that nightly has the issue with the edit dialog not working, I haven't gotten around to fixing it.

**Comment by PaulJManoogian** [comment]
Univrsal, Looking forward to your fix update, as I'm trying to use it for a ShoutCast audio stream that I'm bring in through VLC.  Thanks for a cool tool! Love the Spectralizer, too!

**Comment by AMDITAR** [comment]
Same issue for me on Windows 10.  Can't set any outputs with Tuna 1.5.0 and OBS 25.0.8.

**Comment by univrsal** [comment]
I know, it's a fairly simple fix, but obs 26.0.0 is around the corner and it somehow broke my CI so I'm kinda just waiting for it to come out, because it'll allow me to change some things with the VLC source

**Comment by lunarwolfspirit** [comment]
Is there a way to get access to the build before? Apparently 1.42 was working? I tried the nightly build mentioned earlier, still can't "Add New"

**Comment by AMDITAR** [comment]
I also rolled back to the previous version, as I need it to work until a fix is released.  You can scroll down on the [releases page](https://github.com/univrsal/tuna/releases) to 1.4.2 and download.

**Comment by univrsal** [comment]
Fixed in db58113a073c78b8e828eaa51aaa95769159caf9 and 9bd1a518656d19c2ba45916caee75039b83ef695 I'll try to get the nightlies fixed

**Comment by univrsal** [comment]
Looks like the nightly build fixed itself at least for windows idk what's up with macOS though
