### ISSUE TITLE
use "Window title" ,but nothing happend

### ISSUE THREAD

**Issue by yigexuezha** [univrsal/tuna#63]
use "Window title" ,find from potplayer. but nothing happend,no world in obs

Click on "Tools" at the top of the obs window
Select "Tuna settings"
Select "Window title" as the music source
Select the "Window title" tab
Enter any search term (e.g. Firefox, to search for any window that contains the word Firefox)
Optionally add a search and replace term and/or cut the first or last characters
You're done

**Comment by univrsal** [comment]
I feel like you're just not using the plugin correctly. What is the exact setup? Do you have a text source loading the output of tuna? Also add the obs studio log
