### ISSUE TITLE
Can't seem to get tuna to work

### ISSUE THREAD

**Issue by IntensityGit** [univrsal/tuna#64]
I've been trying to use Tuna but can't seem to get the setup to work when adding a song info output nothing happens and can't seem to change anything, am I doing something wrong or is there an issue?
![OBSTuna](https://user-images.githubusercontent.com/58851674/93224997-a4660e80-f769-11ea-9363-82ea9e4a18f6.gif)

**Comment by AMDITAR** [comment]
Duplicate of #60
