### ISSUE TITLE
Can't make or load output file

### ISSUE THREAD

**Issue by treier57lol** [univrsal/tuna#7]
Trying to load my nowplaying.txt file, OBS crashes when I hit apply. In the logs there is `[tuna] Error writing json at line -1 (col: -1):`. Also I'm unable to make a new file either, says `The provided data is incorrect`. Running OBS under sudo I get 
```
warning: [tuna] Error writing json at line -1 (col: -1): 
warning: [tuna] Error loading output json at line 2 (col: 4): ']' expected near end of file
```
Running Kubuntu 19.04, OBS Studio 24.0.3

**Comment by univrsal** [comment]
Yeah something is wrong with the part that saves the outputs to json, try using the build I linked [here](https://github.com/univrsal/tuna/issues/4#issuecomment-568923362)

**Comment by treier57lol** [comment]
That works great! Loads and saves files no problem! Thank you so much!

**Comment by univrsal** [comment]
np
