### ISSUE TITLE
Song info only updates for 5 seconds, then freezes for 25.

### ISSUE THREAD

**Issue by lindenkron** [univrsal/tuna#70]
I've set it to 1000 ms updates, (once per second) with having tried both %o and %p, running latest version.

It'll update every second counting down song duration left for 5 seconds, then freeze for 25, then count for 5 again.

Is there a rate limit to API calls to spotify and this is why? Or is this something fixable?

**Log:**
https://obsproject.com/logs/zCWcodOWLNrOxd_o

**Video clip of behavior:**
https://streamable.com/7q2ol0

Tuna is awesome by the way, good job!
-Lindenkron

**Comment by univrsal** [comment]
> Is there a rate limit to API calls to spotify and this is why?
Yes, watch the video at end of the Spotify section of the forum post, to fix it.
