### ISSUE TITLE
Not working with Raspberry Pi

### ISSUE THREAD

**Issue by fernandogenis** [univrsal/tuna#71]
Now that the Raspberry Pi (3 & 4) can run OBS. It would be a nice to have this supported in its platform (Raspbian 32 bit).

Tried unzipping the release for linux x64 with no results.

More info on OBS for raspbian:

https://obsproject.com/forum/threads/obs-raspberry-pi-build-instructions.115739/

**Comment by univrsal** [comment]
The release doesn't work, because it uses a different architecture. OBS doesn't officially provide builds for ARM, so I won't either unless someone writes the CI scripts.
