### ISSUE TITLE
Alexa and Spotify

### ISSUE THREAD

**Issue by juan-manuel-alberro** [univrsal/tuna#74]
Hi guys,

I'm playing music in an Alexa device using Spotify and Tuna doesn't detect that.
I'm a premium user so in theory that should be reflected in the API consumed by Tuna, any thoughts on that?

Thanks

**Comment by univrsal** [comment]
As long as you're logged into the same account on both the device that's playing the music and the device that's running the plugin it should work just fine. Please provide your obs studio log and some information about how you set the plugin up.

**Comment by juan-manuel-alberro** [comment]
After the install, I had to restart my PC and now is working :) 
Thanks.
