### ISSUE TITLE
Does it works with ARM architecture?

### ISSUE THREAD

**Issue by Moustiluigi** [univrsal/tuna#75]
I'm trying to install Tuna on a 4Gb RAM Raspberry Pi 4 already running OBS. Due to the '64bit' folder in bin, i doubt that it's compatible with ARM processors, but i'd like to know if the fact that it's not showing up in OBS is related.

**Comment by univrsal** [comment]
Should work, but you'll have to compile it yourself. OBS on a Pi isn't officially supported and not really a great experience so I don't support it either.
