### ISSUE TITLE
Tuna having issues writing certain unicode characters (i.e. Japanese Kanji)

### ISSUE THREAD

**Issue by Zekira** [univrsal/tuna#78]
Hi,

So it seems that not every unicode character is supported or something. For Japanese in particular.

source is in-OBS VLC source

キミニあげる works fine, which is just hiragana and katakana:
![image](https://user-images.githubusercontent.com/11051413/96209475-46b02680-0fa2-11eb-95c0-30fdf061d79a.png)

But when kanji comes into the mix, I think that's where it freaks out.

watson - 渇き:
![image](https://user-images.githubusercontent.com/11051413/96209490-4dd73480-0fa2-11eb-9d40-0d88ad191a96.png)

watson - 春宵闇ニ咲ク
![image](https://user-images.githubusercontent.com/11051413/96209501-53347f00-0fa2-11eb-9aef-62e94a991095.png)

I checked the text file and it seems to also not be written properly:
![image](https://user-images.githubusercontent.com/11051413/96209508-5891c980-0fa2-11eb-984c-853e27dce0b5.png)

If I manually change the text file while the song is running, it's displaying fine in OBS. So I think it has to do with the way Tuna is retrieving the title from the file.
![image](https://user-images.githubusercontent.com/11051413/96209512-5e87aa80-0fa2-11eb-9fa7-cb15492f00b3.png)

**Comment by univrsal** [comment]
Works fine for me, so it's an issue on Windows, which to this day doesn't properly support utf8. Can you try the browser widget? I added it last version you can see [here](https://youtu.be/UcGFiq4n_ww) how it works, you need version 1.5.2 though. Maybe it's just an issue when writing the file.

**Comment by Zekira** [comment]
Still not getting written properly, sadly

![image](https://user-images.githubusercontent.com/11051413/96294185-8ddbfd00-101e-11eb-89c2-bc9f3b292076.png)

The json display upon opening the tuna server localhost:1608 also shows the unsupported characters. (different track from the shot above):
![image](https://user-images.githubusercontent.com/11051413/96294427-eca17680-101e-11eb-88d5-1a686fb5235f.png)

**Comment by univrsal** [comment]
darn, well then it's getting screwed up when receiving the information from VLC. I might get around to debug this tomorrow

**Comment by univrsal** [comment]
Well, now I'm confused it works just fine for me. I think it might be something wrong with your music files. Can you try editing them with [mp3tag](https://www.mp3tag.de/en/)? I just edited one of my files and set the title to 春宵闇ニ咲ク and it works fine:
![grafik](https://user-images.githubusercontent.com/8353672/96339210-be558280-1082-11eb-800a-c06695d2e5a7.png)

**Comment by Zekira** [comment]
*tableflip*

Saving the metadata again with mp3tag seemed to have worked. So I guess it's something with my music files using a different encoding or something?

The titles do show up in explorer properly:
![image](https://user-images.githubusercontent.com/11051413/96357709-e8b24900-1131-11eb-9557-a52c28280c43.png)

However, the source music is from a Japanese composer, so there may be some encoding weirdness happening, I dunno.

Since I can fix it by re-saving the metadata again, I guess this isn't really a bug that needs to be fixed then, but I'm still curious why I need to resave it still. I'm not sure if you're interested in finding out why it's so, but in case you do, the BGMs listed are all actually license-free BGMs, and the specific track above is in this page https://musmus.main.jp/bgm_10.html 

For now I guess I'll just re-tag the titles. Thanks for looking into it.

**Comment by univrsal** [comment]
I downloaded the first one on that page BGM-027 and it doesn't show up correctly. Experimenting shows that the encoding used is "[Shift JIS](https://en.wikipedia.org/wiki/Shift_JIS)", which is one of the many language specific encodings. UTF8 is the de-facto standard and should be used by everyone, because it supports the entire range of Unicode, while these specialized ones only support specific character sets, so you can't use Cyrillic and Japanese in the same file.
As to why it works after saving, mp3tag uses utf8 by default which means that it just converts from JIS to UTF8. I don't know why it doesn't work for me, though. Do you have Japanese language pack installed on Windows, I would assume that that make a difference.

**Comment by Zekira** [comment]
I'm sure I have it installed, though I don't know if it's the same thing as my OS being Japanese already.

So it's a language specific encoding, huh. Makes sense then, for now I'll just do this workaround when using stuff from this composer. Thanks for the help!

**Comment by univrsal** [comment]
> I'm sure I have it installed, though I don't know if it's the same thing as my OS being Japanese already.

Yeah that's the same thing. It'll most likely set the default encoding to JIS. You can make Windows use utf8 as of recently apparently, but at the end of the day the artist has to use it, too:
![image](https://user-images.githubusercontent.com/8353672/96480553-e92e0b00-1229-11eb-8bf0-7f2b0711982f.png)
