### ISSUE TITLE
After installing the plugin, it doesn't show up

### ISSUE THREAD

**Issue by KaiChizuru01** [univrsal/tuna#80]
Hello,

I would like to try using your plugin for VLC, but nothing shows up in my tools after installing v.1.5.3, v.1.5.2, or v.1.5.1. I cannot use v.1.4.2 as for some reason the support for VLC is not there even though this version shows up in my tools. I do not use Spotify so I have no idea what to do.  Please help with this.

**Comment by univrsal** [comment]
I need your obs studio log after you installed the latest version

**Comment by KaiChizuru01** [comment]
So I found the problem a bit... But... it's in the folder... So I don't fully understand...

[2020-10-25 21-11-52.txt](https://github.com/univrsal/tuna/files/5436313/2020-10-25.21-11-52.txt)
![image](https://user-images.githubusercontent.com/33045035/97124681-6e705e80-1707-11eb-978a-c9e31b6781f1.png)
![image](https://user-images.githubusercontent.com/33045035/97124662-5bf62500-1707-11eb-94b4-7b98a7a17680.png)

**Comment by univrsal** [comment]
You're most likely missing the VC runtime, you can get it [here](https://aka.ms/vs/16/release/vc_redist.x64.exe)

**Comment by KaiChizuru01** [comment]
Oh! It works now! Thank you!
