### ISSUE TITLE
How remove .mp4 text? VLC source

### ISSUE THREAD

**Issue by MonkBR** [univrsal/tuna#83]
How remove .mp4 text? VLC source
https://i.postimg.cc/257cLgNL/Screenshot-1.png

**Comment by univrsal** [comment]
you can't right now. Your best bet is to give the file proper title tag with something like [mp3tag](https://www.mp3tag.de/en/download.html)

**Comment by MonkBR** [comment]
> você não pode agora. Sua melhor aposta é dar ao arquivo a tag de título adequada com algo como [mp3tag](https://www.mp3tag.de/en/download.html)

how so mp3tag?

**Comment by univrsal** [comment]
It shows 'mp4' because the file has no proper title tag. If you give it a title tag it'll most likely not use the filename as the title

**Comment by MonkBR** [comment]
> Mostra 'mp4' porque o arquivo não possui uma tag de título adequada. Se você der uma tag de título, provavelmente não usará o nome do arquivo como título

and how do i do that?

**Comment by MonkBR** [comment]
> Mostra 'mp4' porque o arquivo não possui uma tag de título adequada. Se você der uma tag de título, provavelmente não usará o nome do arquivo como título

**Comment by univrsal** [comment]
get mp3tag, drag the video file into mp3tag and set the title

**Comment by MonkBR** [comment]
> get mp3tag, drag the video file into mp3tag and set the title

and how do i do that?

**Comment by univrsal** [comment]
Idk, you'll figure it out
