### ISSUE TITLE
1.5.3 Release Installer exe detected as Trojan Virus

### ISSUE THREAD

**Issue by atorres1929** [univrsal/tuna#85]
It seems the latest release is detected on my machine as a Trojan. **This does not happen on the previous release 1.5.2**.

To save you some googling, it's probably how you compiled it when you shipped it:

https://stackoverflow.com/questions/61958729/codeblocks-mingw-windows-defender-trojanwin32-fuery-ccl

Hope this helps!

![image](https://user-images.githubusercontent.com/9524075/98894593-55cfaa80-2462-11eb-878c-aa92816a5154.png)

**Comment by univrsal** [comment]
Not much I can do, is that windows defender? I scanned it myself and it was fine. If it's any other anti virus program, I'd just blame it on that. Generally all anti virus programs are trash and just get in the way.

**Comment by atorres1929** [comment]
Yeah that's windows defender. I agree, it's a false positive. Just figured I'd let you know.

Strange that the most recent release flagged it, but not the previous release.

Anyways yeah, can close this.

**Comment by univrsal** [comment]
Does it do the same if you scan the zipped release?

**Comment by atorres1929** [comment]
I can check for you a bit later in the day, but I suspect not. Will let you know

**Comment by atorres1929** [comment]
@univrsal sorry man, I forgot to respond. The zipped version seems to be fine. I think it's largely because it's an executable form.

**Comment by univrsal** [comment]
I guess it's just the installer then. It'll probably be gone once I release a new version, though.

**Comment by atorres1929** [comment]
Sounds good.
