### ISSUE TITLE
Request - Multiple VLC sources

### ISSUE THREAD

**Issue by Gamertech** [univrsal/tuna#86]
**Describe the bug**
Tuna works perfectly with a single VLC source pulling from a playlist. I'd like to run separate playlists for different scenes (starting/break/etc), but Tuna only pulls data for a single source.

~When changing to another scene with Tuna, the on-screen display will continue to show the last song from the original scene, and the progress bar will continue indefinitely, off the edge of the screen.~

~As above, changing the source in Tuna settings has no effect without restarting OBS, and then ignores other sources again.~

~**To Reproduce**~
~Steps to reproduce the behavior:~
~1. Setup a Tuna display and different VLC sources in different scenes~
~2. Set Tuna settings to 1 source~
~3. Play a track in one scene, then swap to another scene~
~4. Tuna display freezes at last song and progress bar continues infinitely~

**Expected behavior**
Tuna works with multiple sources (1 source per scene), potentially updating the same txt files with the data from the new source after changing scenes.

Tuna settings currently lets you pick a VLC source. Maybe show a list of scenes with VLC sources and pick ones you want Tuna to monitor?

Thanks

**Comment by platinumazure** [comment]
I just ran into this myself. It would be really nice if we could have Tuna switch between different playlists, either at the scene level or through some hotkey-able action.

As a workaround, it would be great if we could switch between playlists in the Tuna settings without having to restart OBS completely. Restarting OBS completely is not an option in the middle of a stream 😄 Even having Tuna pick up the new VLC source when Tuna is stopped and started would be an improvement over the current experience.

**Comment by univrsal** [comment]
You can now use multiple sources per scene per scene collection. You can test it with [this](https://github.com/univrsal/tuna/actions/runs/1178073380) build
https://up.vrsal.de/66hqtik4.webm
Each scene has a list of vlc sources that you can set in the tuna settings. The plugin will use the first one in the list, but you can cycle back and forth via hotkeys.
