### ISSUE TITLE
I want to translate the plugin into Brazilian Portuguese

### ISSUE THREAD

**Issue by gabrielpastori1** [univrsal/tuna#87]
Just give me instructions to do the translation

**Comment by univrsal** [comment]
1. Fork the repository
2. Create pt-BR.ini in this [folder](https://github.com/univrsal/tuna/tree/master/data/locale)
3. Translate everything from [en-US.ini](https://github.com/univrsal/tuna/blob/master/data/locale/en-US.ini) to pt-BR.ini
4. Create a [pull request](https://docs.github.com/en/free-pro-team@latest/desktop/contributing-and-collaborating-using-github-desktop/creating-an-issue-or-pull-request#creating-a-pull-request)
