### ISSUE TITLE
MP3 with cover in VLC source crashes OBS

### ISSUE THREAD

**Issue by COOLIGUAY** [univrsal/tuna#9]
Add an MP3 file with cover to an VLC source crashes OBS.
MP3 without cover run ok.

**Comment by univrsal** [comment]
I need the crash log otherwise I can't help you

**Comment by COOLIGUAY** [comment]
My apologies, i forgot to attach it

https://obsproject.com/logs/G4_v9JdIbTcy6TxG

VLC version 2.2.6

**Comment by COOLIGUAY** [comment]
Tried versions 2.2.6, 2.2.8, 3.0.0 and 3.0.8.

With VLC Player 2.2.8 crashes too.

Since version 3.0.0 it works ok.
Now, with the latest version 3.0.8 installed, without issues.

OBS previously had problems with version 3 or higher, so i left the previous version and did not update it.

It may be good to indicate as a requirement that users consider install a version of VLC Player 3.0.0 or higher.

I'm sorry i haven't tried this before.

Thank you so much for adding this feature in your amazing plugin!

**Comment by univrsal** [comment]
I mean 2.2.6 is pretty outdated, no one should be using that anyways. I'll add a warning on the release page for now, though.
