### ISSUE TITLE
[Win] Integrate GlobalSystemMediaTransportControls

### ISSUE THREAD

**Issue by orion78fr** [univrsal/tuna#91]
GlobalSystemMediaTransportControls is the thing that appear on Windows 10 when you play/pause or change volume :

![image](https://user-images.githubusercontent.com/8122888/99350645-2e803f80-289f-11eb-94be-bad0491d9db7.png)

You can access its info with the [GlobalSystemMediaTransportControlsSessionManager](https://docs.microsoft.com/en-us/uwp/api/windows.media.control.globalsystemmediatransportcontrolssessionmanager?view=winrt-19041) class.
It has multiple sessions (one for each media player on the system) but current one (`GetCurrentSession()`) should be the one you most likely want to control (the one that currently responds to media control keys).

When you have a [GlobalSystemMediaTransportControlsSession](https://docs.microsoft.com/en-us/uwp/api/windows.media.control.globalsystemmediatransportcontrolssession?view=winrt-19041), you can control the playback (`TryPlayAsync()`, `TryPauseAsync()`, `TrySkipPreviousAsync()`, `TrySkipNextAsync()`) and you can `TryGetMediaPropertiesAsync()`, which give you a [GlobalSystemMediaTransportControlsSessionMediaProperties](https://docs.microsoft.com/en-us/uwp/api/windows.media.control.globalsystemmediatransportcontrolssessionmediaproperties?view=winrt-19041) which holds all the current song info (title, artist, album...).

I think this could be a great addition because it integrates smoothly with a lot of players (even firefox !) and avoids making calls to APIs like Spotify.

**Comment by univrsal** [comment]
I'll take a look at it

**Comment by univrsal** [comment]
The API only works for WinRT programs, which tuna is not. The only way to access the API through a normal C++ program is with https://github.com/microsoft/cppwinrt , which doesn't seem to play nice with cmake so I'll probably not bother with this.
