### ISSUE TITLE
Soundtrack by Twitch integration

### ISSUE THREAD

**Issue by tatunts** [univrsal/tuna#92]
Hello!

First of all, thanks for this great app :)

Is it possible to integrate the new Soundtrack by Twitch music app in Tuna? https://help.twitch.tv/s/article/soundtrack?language=en_US

It seems like a great DMCA free music player...

Thanks!

**Comment by orion78fr** [comment]
I'm pretty sure the current song name is automatically displayed under the stream and ppl can disable it if they want in the player settings.

![image](https://user-images.githubusercontent.com/8122888/99540298-a0e04500-29af-11eb-9601-ee739239ea96.png)

**Comment by tatunts** [comment]
Yes! But I don't want to use their OBS plugin and mess with my audio channels and such. I'm using it like I use Spotify: routed to a "music" audio device and added as a source on OBS. I love using Tuna to display the current song and album art, I wish I could still use it now with Twitch Soundtrack :) Here's an example, you can see my overlay on the bottom left corner: https://clips.twitch.tv/BoldYummyHamsterFunRun Thanks a lot!

**Comment by orion78fr** [comment]
Then it's not DMCA-free, that's why I was pointing it out. 

```Music from Soundtrack is intended to be included only in your live streams. We separated the music into its own audio channel so you can play music on stream without worrying about your archives being muted or receiving takedown requests against your Twitch channel (or wherever else your content may go!)

If portions of your VODs are being muted, then you most likely don’t have Soundtrack configured correctly. When Soundtrack is not configured correctly, music from Soundtrack may be included in your VODs and Clips, and those sections could then be muted or deleted by Audible Magic, our system that detects music in your recorded content. ```

**Comment by tatunts** [comment]
Oh ok, got it. I was using Spotify to play Harris Heller's playlists (https://twitter.com/HarrisHeller), never got a single copyright strike since. Thanks a lot!

**Comment by univrsal** [comment]
How would the integration work? Do they have an API for it?

**Comment by orion78fr** [comment]
I don't think so, it seems it's still a suggestion : https://twitch.uservoice.com/forums/310213-developers/suggestions/41519041-provide-soundtrack-now-playing-information-for-a-s

**Comment by univrsal** [comment]
When there's an API I might consider this, but for now there's not much to do.
