### ISSUE TITLE
Crash on OBS exit

### ISSUE THREAD

**Issue by orion78fr** [univrsal/tuna#95]
**Describe the bug**
OBS crashed on exit.

**Log**
[2020-11-25 13-18-30.txt](https://github.com/univrsal/tuna/files/5599982/2020-11-25.13-18-30.txt)
[Crash 2020-11-26 02-37-34.txt](https://github.com/univrsal/tuna/files/5599983/Crash.2020-11-26.02-37-34.txt)

**Additional context**
I have a shitty router that sometimes ban domains until I reboot it (I still don't know exactly why).
The spotify API couldn't be contacted so token refresh was impossible.
(Maybe an exponential backoff retry policy could be used to avoid spamming the logs)
That's probably what caused the crash, it was trying to refresh the token, and couldn't.

**Comment by univrsal** [comment]
The exit process is broken for some reason, VLC also crashes when the source is stopped on exit. I'll look into it

**Comment by univrsal** [comment]
You can try the latest nightly, it should at least stop the spamming

**Comment by darkwolfie37** [comment]
I have the same issue

**Comment by univrsal** [comment]
I think this one's fixed?
