### ISSUE TITLE
How to enable VLC support if accidentally disabled by user?

### ISSUE THREAD

**Issue by patiszejuicebox** [univrsal/tuna#98]
Just downloaded Tuna. So far, it's working with Spotify. However, I also want it to work with VLC, as I have it, but I accidentally pressed the wrong button to enable once I opened OBS after the download and implementation.

**Comment by univrsal** [comment]
What version did you download? That option doesn't exist anymore

**Comment by patiszejuicebox** [comment]
v1.4.2

**Comment by univrsal** [comment]
Where did you even get that? This is the latest version https://github.com/univrsal/tuna/releases/tag/v1.5.4
