### ISSUE TITLE
[Request] Shoutcast/Icecast

### ISSUE THREAD

**Issue by JJK1231** [univrsal/tuna#99]
Hi,

Can you add a Shoutcast of Icecast stream??

**Comment by univrsal** [comment]
Can you provide me with an example stream that you'd be using?

**Comment by rayrrr** [comment]
Hi @univrsal I request that we reopen this issue and add this feature as well! Basically any Icecast stream running on version 2.4.1 or greater will offer a JSON endpoint at `/status-json.xsl` that provides a response like this where artist/song title info can be extracted:

```
{
    "icestats": {
        "admin":"icemaster@localhost",
        "host":"<ICECAST SERVER URL HERE>",
        "location":"Earth",
        "server_id":"Icecast 2.4.4",
        "server_start":"Thu, 11 Mar 2021 04:19:16 -0800",
        "server_start_iso8601":"2021-03-11T04:19:16-0800",
        "source":{
            "audio_info":"bitrate=128",
            "bitrate":128,
            "genre":"Live Mix",
            "listener_peak":20,
            "listeners":12,
            "listenurl":"<ICECAST SERVER URL HERE>:80/stream",
            "server_description":"This stream is online for testing purposes!",
            "server_name":"Unspecified name",
            "server_type":"audio/mpeg",
            "server_url":"https://www.mixxx.org",
            "stream_start":"Wed, 08 Sep 2021 20:17:17 -0700",
            "stream_start_iso8601":"2021-09-08T20:17:17-0700",
            "title":"<THIS IS WHERE TO FIND SONG TITLE AND ARTIST NAME>",
            "dummy":null
        }
    }
}
```

Please let me know if I can provide additional support to this as an Icecast user.

**Comment by univrsal** [comment]
Do you have an example station so I can test this? I just tried this with four stations from http://dir.xiph.org/ and all of them sent one megabyte of metadata and none of them contained any useful information. This doesn't really seem like a feasible way of retrieving metadata if it wastes so much bandwidth.

**Comment by rayrrr** [comment]
Hi @univrsal I can provide an example station URL, but privately. I created a private repo with the live Icecast metadata URL in the README and invited you as a collaborator. Have a look there for it. Thanks!

**Comment by univrsal** [comment]
I don't think I was invited to anything

**Comment by rayrrr** [comment]
@univrsal https://github.com/rayrrr/icecast_server_example_4_tuna is the private repo I invited you to check it out

**Comment by univrsal** [comment]
![image](https://user-images.githubusercontent.com/8353672/132951459-e49e3a4c-53ed-4d22-86c7-b5e40103586c.png)

**Comment by rayrrr** [comment]
Whoa @univrsal dies that screenshot mean you got it working already? Let me know how else I can help

**Comment by univrsal** [comment]
Yes, you test it [with these builds](https://github.com/univrsal/tuna/actions/runs/1224530849).

**Comment by rayrrr** [comment]
@univrsal I tested it on Linux and it works great. Thank you!

**Comment by rayrrr** [comment]
@JJK1231 if you still want to test Icecast/Shoutcast support too, use the link to the test builds posted two comments above this one!

**Comment by JJK1231** [comment]
@univrsal, Thanks for adding this! I Go test it right now!

**Comment by rayrrr** [comment]
@univrsal upon further testing I am getting a strange result: after about an hour, it stops working. In particular, Tuna seems to stop updating the text file with the song info in it, even though the Icecast stream is still running. Once that occurs, OBS itself becomes buggy and sometimes even crashes. It didn't used to crash on me even after running for many hours at a time. I am running a local Icecast server on the same machine as OBS so I'm sure the Icecast server can handle the frequent metadata HTTP requests...trying to figure out if it's an OBS issue, or something with my system (Debian-based), or with Tuna at this point, figured I'd mention it...

**Comment by univrsal** [comment]
Might be a memory leak

**Comment by rayrrr** [comment]
I _really_ want this to work and tracking down a memory leak sounds like a fun challenge. Does Tuna write to logs? Should I build it locally with debugging enabled? Or can you give me any other clues as to where in the code to look for leaks? I have a basic working knowledge of C++ and I'd like to help.

**Comment by univrsal** [comment]
I think I already know where it's leaking

**Comment by rayrrr** [comment]
@univrsal give me a clue! We can race to the finish to see who gets the PR to fix the leak up first :)

**Comment by univrsal** [comment]
https://github.com/univrsal/tuna/commit/af8c3253956d382837eaf2dfa436f6afe11f9964

**Comment by rayrrr** [comment]
Nice. A one-liner, literally with the string `easy` as part of it. Good stuff! Testing all day, will report back.

**Comment by rayrrr** [comment]
@univrsal been running smoothly on the latest build for 24 hours straight without any disruption, so I'd say the memory leak issue is resolved. Just bought you a week's worth of coffees. Thanks again. I encourage you to tag a release with this improvement! :smiley:

**Comment by univrsal** [comment]
Thank you! I will probably make a new release once I address #146
